### ISSUE TITLE
DID Upgrade support

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#1066]
Add support for the new DID Upgrade functionality.

We should also add additional conceptual documentation (beyond the API docs) to introduce this new feature, underlying concepts, and particularly the paid nature of non-test ledger-based DIDs (ie, ION MainNet).

Languages:
- [x] CLI https://github.com/trinsic-id/sdk/pull/1075
- [x] Docs
- [x] .NET
- [x] Dart
- [x] Go
- [x] Java
- [x] Python
- [x] Ruby
- [x] Swift https://github.com/trinsic-id/sdk-swift/pull/45
- [x] Typescript

**Comment by fundthmcalculus** [comment]
I'll take care of swift, I now have the generator code working for swift automatically. 👍

**Comment by fundthmcalculus** [comment]
https://github.com/trinsic-id/sdk-swift/pull/45
