### ISSUE TITLE
Confirm `COUNT(_)` search queries work on all languages

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#1113]
Verify SQL search queries support the `COUNT()` function, since some languages appear to have issues.

Languages:
- [x] CLI (confirmed by @tmarkovski )
- [ ] ~Docs~ (irrelevant)
- [x] .NET
- [ ] Dart
- [ ] Go
- [ ] Java
- [ ] Python
- [ ] Ruby
- [ ] Swift
- [ ] Typescript

**Comment by geel9** [comment]
I'm confused -- what about this is language-specific?

Are certain languages mangling the queries before they get sent to the backend or something?

**Comment by fundthmcalculus** [comment]
> I'm confused -- what about this is language-specific?
> 
> Are certain languages mangling the queries before they get sent to the backend or something?

This is a verification on all languages to ensure they are compatible, which they should be. In some cases, the protobuf deserialization can be different and that has created issues before. #justbecauseyoureparanoiddoesntmeantheyrenotouttogetyou 😁

**Comment by tmarkovski** [comment]
I tend to agree with Josh, this seems like we're ensuring a simple string is being sent correctly. Not an efficient allocation of efforts.

**Comment by fundthmcalculus** [comment]
I'm doing some spot checks on this, not necessarily a full suite of tests.

**Comment by fundthmcalculus** [comment]
counting templates works, I wonder if it is `COUNT()` on templates vs `COUNT()` on wallet items. Will verify this as part of the front end sorting work. If everything plays nice, I'll close this ticket.

**Comment by fundthmcalculus** [comment]
`listCredentialTemplates` does not work with `COUNT()`, `searchCredentialTemplates` does... 🤦

**Comment by tmarkovski** [comment]
> `listCredentialTemplates` does not work with `COUNT()`, `searchCredentialTemplates` does... 🤦

They are conceptually different. Ideally, `list` should only take a (WHERE) filter, not the entire query, since it will attempt to parse the response as a specific object. COUNT changes that, so it fails. It's an idea we need to revisit linked to the efforts of improving the paging API vs exposing SQL
