### ISSUE TITLE
Enable `useOptionals=all` for `ts-proto`

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#1163]
This will enable us to quit using `[MessageType].fromPartial()` at the risk of serializing invalid message numbers over the wire. Since we are deserializing all our own messages, this should not matter. 

* Relevant link to `ts-proto` docs: https://github.com/stephenh/ts-proto#supported-options
* Once [Exact Types](https://github.com/microsoft/TypeScript/issues/12936) are adopted, it will be better
- [x] Verify what happens if you pass in a "bonus" field
- [ ] ~Verify sending a "bonus" field over the wire (if the transport layer doesn't catch it above)~

**Comment by geel9** [comment]
> Since we are constructing all our own messages, this should not matter.

I'm not sure I agree -- our customers will be constructing messages constantly and passing them to our API. Or am I misunderstanding?

**Comment by fundthmcalculus** [comment]
> > Since we are constructing all our own messages, this should not matter.
> 
> I'm not sure I agree -- our customers will be constructing messages constantly and passing them to our API. Or am I misunderstanding?

Ambiguous statement. Clarified initial ticket.

**Comment by fundthmcalculus** [comment]
Typescript enforces object literals to not have "bonus" fields.

**Comment by fundthmcalculus** [comment]
This is already done.
