### ISSUE TITLE
Assign Issues to Project actions is failing

### ISSUE THREAD

**Issue by tmarkovski** [Dentity-Development/dentity-ecosystems-sdk#1188]
### Reproduction steps

See latest runs.

Not sure if we still need this action. Are we utilizing github Projects and Milestones @janpieterz ?

**Comment by janpieterz** [comment]
Funny, I have it on my list to check it out next week. Will take a peeky

**Comment by fundthmcalculus** [comment]
We no longer need this action. I'll remove it.
