### ISSUE TITLE
Bug Report: Templates not associated to Auth Token returned for SearchCredentialTemplatesRequest

### ISSUE THREAD

**Issue by dnaicker** [Dentity-Development/dentity-ecosystems-sdk#1189]
### Reproduction steps

1. When doing a searchTemplate call using `SELECT * FROM c`, in typescript `const searchResponse = await trinsic.template().search(SearchCredentialTemplatesRequest.fromPartial({ query: (request.payload as any).query }));`,  

Showing call from front-end
<img width="532" alt="image" src="https://user-images.githubusercontent.com/7840952/205650791-1819f78c-d361-4526-a785-6423a11f9742.png">
<img width="683" alt="image" src="https://user-images.githubusercontent.com/7840952/205652164-a404eb66-3360-4f84-9a56-bc32ee893f95.png">

2. I receive  a lot of data returned not related to the templates I have created.
<img width="985" alt="image" src="https://user-images.githubusercontent.com/7840952/205651170-a0b28749-894d-4109-a40d-453d475d67ed.png">

3. I am using the auth_token that is on my dashboard

An example of a template I created recently that I am not able to find using my auth_token: `https://schema.trinsic.cloud/default/denver-test-b0c7c924-6cea-47c9-a3f3-fb5265d7f1cd`

**Comment by fundthmcalculus** [comment]
These look like the `default` ecosystem contents. Are you working inside your own ecosystem, or logging into the default ecosystem (not providing an ecosystem on the `SignInRequest` object)?

**Comment by dnaicker** [comment]
I am using `loginConfirm`, signing in with `email` address which returns `AccountProfile` which contains `auth_token`. I use this auth_token throughout all my requests and am currently using it to list credentials in my wallet, which does display any new credentials I complete from the long list of credential templates displayed. 

Although the credential templates I create don't show up when I run using my auth_token.

**Comment by janpieterz** [comment]
Hi @dnaicker , I've dug into things a bit. If you're letting a user log-in (so not using your provider token from the Dashboard for, e.g. some background task) you'll want to use the following code-flow:


```ts
const loginResponse: LoginResponse = await service.account().login(
      LoginRequest.fromPartial({
        email,
        //Change this to your ecosystem id
        ecosystemId: "default",
      })
    );
```

```ts
//Get the below from user input
const securityCode = "";
const authToken = await service
      .account()
      .loginConfirm(loginResponse.challenge, securityCode);
```

**Comment by dnaicker** [comment]
The authtoken I am using is for the user currently logged in which is my email address and not company organisation.

I have double checked against the dashboard api token and they are not the same.

It is the same auth token that I am using to retreive credentials against wallet and it displays the credentials correctly.

**Comment by dnaicker** [comment]
I am currently setting my organisition details

`	const trinsic = new TrinsicService();
	
	// set orginisation auth token
	trinsic.setAuthToken(process.env.AUTHTOKEN || "");

	// retrieve email
	// todo: validate that email field was sent using joi
	// todo: verify no escape characters in request

	// response otp (sent to email) and challenge
	const loginResponse = await trinsic.account().login(
    LoginRequest.fromPartial({
        email: `${request.params.email}`,
    })
	);
`

![image](https://user-images.githubusercontent.com/7840952/205858964-360955bc-82c0-4b7a-a606-f3b961e529e4.png)

Instead of using `trinsic.setAuthToken`, which has our organisation auth_token:
`trinsic.setAuthToken(process.env.AUTHTOKEN || "");` 

I will use set to default
`LoginRequest.fromPartial({
        email: ${request.params.email},
				ecosystemId: "default",
 })`

Do I not just need the ecosystemId of my organisation instead of default? 

I would need to implement the getEcosystem calls as well to get the ID because it is not on the dashbaord

**Comment by dnaicker** [comment]
Thanks @janpieterz  it works now, I removed all references of the previous `trinsic.setAuthToken(process.env.AUTHTOKEN || "");` and am using `ecosystemId` in `LoginRequest.fromPartial` and using the `auth_token` returned from that

**Comment by janpieterz** [comment]
Awesome! I'll close this ticket then. 

In case you're doing any background (backend) processing (e.g. provisioning templates, issuers, issuing credentials) where you don't have a user session active, you'll likely want to store respective authentication tokens (e.g. for issuers, or your main provider token provided through the Dashboard) and use the `trinsic.setAuthToken()` logic. Then you should not need to use the `login` and `loginConfirm` methods.

**Comment by dnaicker** [comment]
Yes once I have `auth_token` I continously re-utilise it with `trinsic.options.authToken`, does that operate the same as `trinsic.setAuthToken()`?

**Comment by fundthmcalculus** [comment]
That works the same, that's fine. `setAuthToken` dates back to when we couldn't set certain things directly.

**Comment by dnaicker** [comment]
> Awesome! I'll close this ticket then.
> 
> In case you're doing any background (backend) processing (e.g. provisioning templates, issuers, issuing credentials) where you don't have a user session active, you'll likely want to store respective authentication tokens (e.g. for issuers, or your main provider token provided through the Dashboard) and use the `trinsic.setAuthToken()` logic. Then you should not need to use the `login` and `loginConfirm` methods.

If you're using the same auth_token as organisation to issue credential, how do you ensure traceability for `self-attested` credentials? Would the auth_token need to be from that individual? Can one do traceability of creation of credential to see the issuer was `self-attested`? How would traceability be done?

**Comment by tmarkovski** [comment]
What do you mean by self-attested credentials? An issuer signing a VC for themselves and claiming to be a different subject?

@dnaicker The auth token is only used to authenticate with the API and ensure access to the correct wallet signing keys. Once the VC is created, it's signature in the `proof` data should be considered a secret, because anyone with a possession of it can generate proof of possession. This is why each gets their own wallet where secret VCs are stored, and allows generation of proofs.

**Comment by dnaicker** [comment]
Thank you @tmarkovski the insight into how VCs operate helps a lot.

The expression "self-attested" is from the conversation on slack with Trinsic:
My Question:
```
Can an issuer create and store credentials against themselves?
	- Wouldn't this be a breach or conflict or interest
	- Of what value does the credential have, if an issuer can makeup any credential they want and then verify that towards a schema they are aware of that another institution utilises
	- Do we need to check that the credential comes from that institution that verifies it?
	- Is there a way to do this currently?
	- Can I compare issuer did key?
```

The response was:
```
Yes, an issuer can create and store credentials against themselves. “Self-attested” credentials are just credentials signed by one’s own private keys — so not only can issuers “store credentials against themselves”, but also end-users can do this as well. It’s akin to simply claiming something about yourself.
If you need more trust beyond just what someone claims about themselves, that’s where obtaining credentials from a 3rd-party issuer comes into play. And how do you trust that issuer? Governance. So governance is a key thing to consider for trustworthiness of credentials. In addition, each verifiable credential is cryptographically signed by an issuer, along with the issuer’s identifier. [In order to be trustworthy, you should check the issuer ID](https://docs.trinsic.id/learn/concepts/credentials/#issuer-id).
About the other questions, I’m checking them out
```
 
 A different question I wanted to pose, during the verification step, does a business service need any additional logic to confirm the credential proof upload is valid in terms of it being the correct one issued rather than say a generic one that may contain exactly all the schema fields but issued by an authority figure that might be a suspicious actor in the system?
 
Are these more or less a complete list of checks to be done:

1. Check the registered issuer is associated to trusted registered centralised service authority
2. Check all schema fields uploaded are according to the ones expected to extract values and populate answers for a user to access a service (based no the user selection to have those fields provided and whether they would have manually enter them later on based on requirements of business service)
3. Do we store some evidence that a credential proof was used or do we just focus on the data that was captured? If so, what part of the credential proof do we use as a link, would it be DID related?
4. Is there any other link or reference to check for to validate the credential proof aligns to the business service it is being uploaded against?
