### ISSUE TITLE
Remove Newtonsoft from C# SDK

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#134]
@tmarkovski @michaeldboyd It looks like `newtonsoft` is used/included by some of our nuget packages. Is there a reason to actually remove this?

**Comment by fundthmcalculus** [comment]
https://github.com/trinsic-id/okapi/pull/176

**Comment by fundthmcalculus** [comment]
https://github.com/trinsic-id/sdk/pull/137

**Comment by tmarkovski** [comment]
If it's not required by the SDK, it shouldn't be a dependency
