### ISSUE TITLE
Go SDK should accept a context for all remote calls

### ISSUE THREAD

**Issue by romanlevin** [Dentity-Development/dentity-ecosystems-sdk#147]
Currently the Go SDK uses an internal `context` object for all remote calls. Among other things, this means users of the SDK can't specify a timeout or cancel a call to Trinsic.
https://github.com/trinsic-id/sdk/pull/155

**Comment by fundthmcalculus** [comment]
@romanlevin for my understanding, what you want is to be able to provide, or alter, the `context` object used?

**Comment by romanlevin** [comment]
@fundthmcalculus in general yes, but specifically it's common (universal?) practice in Go API design to accept a `context` object as the first argument for every blocking function.

**Comment by fundthmcalculus** [comment]
Right on. I didn't for the initial prototype, will add that as part of the
async support that's coming soon.

**Comment by fundthmcalculus** [comment]
@romanlevin just added context support to `main`. Please test again.
https://github.com/trinsic-id/sdk/pull/155
