### ISSUE TITLE
Use production endpoints as default in SDK

### ISSUE THREAD

**Issue by tmarkovski** [Dentity-Development/dentity-ecosystems-sdk#175]
Updates required for all SDK

- [x] Change default endpoint to `prod.trinsic.cloud:443` with TLS support
  - [x] Node
  - [x] Browser
  - [x] Python https://github.com/trinsic-id/sdk/pull/184
  - [x] Go https://github.com/trinsic-id/sdk/pull/200
  - [x] NET
  - [x] Swift
  - [x] Java https://github.com/trinsic-id/sdk/pull/187
  - [x] Android - covered by Java already
  - [x] Ruby

Additionally, it is recommended that SDKs take a configuration object/struct/map with fields to override defaults. The fields required with this effort are:
- `endpoint` - the gRPC endpoint to use in format `server:port`. If required by the SDK, it should be reformatted internally to `https://server:port`.
- `use_tls - boolean indicating if TLS should be used. Default value is `true`

**Comment by fundthmcalculus** [comment]
How about we define this configuration object in the protobuf, so that it is consistent for all languages?

**Comment by tmarkovski** [comment]
> How about we define this configuration object in the protobuf, so that it is consistent for all languages?

Great idea.

**Comment by fundthmcalculus** [comment]
https://github.com/trinsic-id/sdk/pull/184
