### ISSUE TITLE
Generic error is thrown when trying to create a wallet with a security code from an invitation

### ISSUE THREAD

**Issue by Franklin89** [Dentity-Development/dentity-ecosystems-sdk#180]
A generic error is thrown when trying to create a wallet with a security code from an invitation. I do receive the email with the same security code that is also in the `inviteResponse.InvitationId`. I have tried with the same provider wallet and also with a new provider wallet.

**To Reproduce**
![image](https://user-images.githubusercontent.com/4151467/140290409-91ee0156-dfc6-428a-b922-f31b90548417.png)
![image](https://user-images.githubusercontent.com/4151467/140290363-197c9a12-b16a-4513-bc4f-6c030a15977e.png)

**Expected behavior**
The wallet should be created for the user that has been invited without an error.

**SDK (or CLI) you are using**
 - SDK: .NET
 - Version: 1.0.1
 - OS: Windows

**Comment by fundthmcalculus** [comment]
@Franklin89 we are working on adding more descriptive error types to the SDKs for errors that occur at the SDK level. That error sounds like a potential bug with the underlying service ( @tmarkovski thoughts? ) which you shouldn't have seen. Part of showing those errors in the EAP program is it helps us to identify bugs that are coming from a lower level than the SDK layer. Would you prefer that all `Grpc` errors are wrapped in a general `TrinsicSDKError` exception?

**Comment by Franklin89** [comment]
If the exceptions are wrapped in an SDK error the important thing will be to keep the stack trace. This would make it simple for both sides. For the developer to implement a specific catch statement, searching the logs for the SDK errors and if the stack trace is intact it is easy to find the original error inside of the SDK.
