### ISSUE TITLE
CLI Packages

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#20]
- [ ] Package Support
  - [ ] Homebrew for Mac
  - [ ] Chocolatey for Windows
  - [ ] Cargo for Rustup
  - [ ] (descoped) ~~apt-get for Linux~~

**Comment by fundthmcalculus** [comment]
How does this relate to the other packaging work? Aka, `pip`, `nuget`, etc?
