### ISSUE TITLE
Implement `register-egf` command in CLI

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#202]
![image](https://user-images.githubusercontent.com/22651660/141724031-c4a04c3f-8f1b-4bc4-b5c2-4c2da8073b8e.png)

Referring to the cli.yaml file, the `register-egf` command has not been implemented

**Comment by tmarkovski** [comment]
@michaeldboyd Is this still an open issue?
