### ISSUE TITLE
Docs - Services Technical Spec

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#21]
- [x] Authentication/ Profile Management https://github.com/trinsic-id/sdk/pull/27 
- [x] Wallet Service https://github.com/trinsic-id/sdk/pull/27
- [x] Provider Service https://github.com/trinsic-id/sdk/pull/27
- [x] Add additional Conceptual Docs
- [x] JS references in walkthrough @michaeldboyd https://github.com/trinsic-id/sdk/pull/46
- [x] C# references in walkthrough @michaeldboyd https://github.com/trinsic-id/sdk/pull/30
- [x] Better walkthrough narrative @michaeldboyd #37 
- [x] onboarding page for how to get set up  @michaeldboyd https://github.com/trinsic-id/sdk/pull/37
- [x] FAQ Technical Questions  #37 @michaeldboyd

**Comment by tmarkovski** [comment]
I suggest we remove `Add API Data model in reference` item for now. We won't need to describe it in details so much, and the only needed data contract is already documented - https://trinsic-id.github.io/sdk/reference/profiles/#profile-data-format

Same with `SSI Concepts`, unless you have something ready.

**Comment by michaeldboyd** [comment]
I've added the API Data model as a stretch goal. agreed it isn't as high prio
