### ISSUE TITLE
Java Onboarding

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#219]
As a new user I can 
- [x] Follow steps to download a sample Android application with Trinsic's SDK added and get it running  https://github.com/trinsic-id/sdk/issues/220
- [x] Follow steps on how to add Trinsic's java SDK to my Maven and/or Gradle toolchain in my project
- [x] Follow steps to run a demo application that goes through the walkthrough

**Comment by fundthmcalculus** [comment]
This should already be done. The Java instructions (not android) already exist and got merged last night.
