### ISSUE TITLE
Verify SDK unit test coverage

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#259]
### Requirements
* Report what percentage of the SDK code (by language) is covered in tests
* Ideally, this should be reported as a github metric, but *not* be a blocking requirement (too easy to game, and pointless).
* Goal is to achieve 100% coverage in all languages, but not as part of this issue.
* Read the junit results artifacts and check for consistent test names/namespaces, correcting for language naming conventions.
* We'll use `PascalCase` for the report, since that is the easiest to read.
* Let's try to use shields.io to display the code coverage on the front page of the repository

- [x] .NET
- [x] Go
- [x] Java
- [x] Dart
- [x] Python
- [x] Ruby
- [x] Swift https://github.com/trinsic-id/sdk-swift/issues/17
- [x] Typescript

**Comment by musaib072** [comment]
i will work on this issue . which folder/file  should i open to solve this issue ?

**Comment by fundthmcalculus** [comment]
thanks for the interest, @musaib072 ! This is a CI/CD pipeline setup, so it would be under the `.github` folder for the actions. You'll see that all the test result report .xml files are named similarly, so it should be easy to create a script that collects all of them and looks for similar test names. Ignore `snake_case` vs `camelCase` vs etc, and any prefixed form of `test`, since some languages require that.

**Comment by musaib072** [comment]
@fundthmcalculus  where will i find report.xml file

**Comment by musaib072** [comment]
@fundthmcalculus  could you please tell the steps  to get report.xml files

**Comment by fundthmcalculus** [comment]
https://app.codecov.io/gh/trinsic-id/sdk/new <- let's use codecov to track the output coverage levels. We can then use badges on github to see the coverage percentage.

**Comment by fundthmcalculus** [comment]
https://docs.codecov.com/docs/merging-reports <- this will handle merging across all actions
