### ISSUE TITLE
CLI 1.1.0 fails to create account

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#264]
Sorry for the error barf, figured it was better than having all of it on a single line.

$> trinsic account login --alias test

thread 'main' panicked at 'Create Wallet failed: Status { code: Unimplemented, message: "Service is unimplemented.", metadata: MetadataMap { headers: {"date": "Tue, 07 Dec 2021 00:03:46 GMT", "content-type": "application/grpc+proto", "content-length": "0", "request-context": "appId=cid-v1:6e9498ac-3318-417c-8df4-33ec564291a1", "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400, h3-28=\":443\"; ma=86400, h3-27=\":443\"; ma=86400", "cf-ray": "6b997e269e253b39-SJC", "x-envoy-upstream-service-time": "0", "cf-cache-status": "DYNAMIC", "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", "report-to": "{\"endpoints\":[{\"url\":\"https:\/\/a.nel.cloudflare.com\/report\/v3?s=veG1IKvCrBNa8T0DwRFrPzv4M8DB5h3taTjc4em4779rd9yQLTy81Q6%2FG2c7LYpc2DQ2Kb8pSXxY4m%2FyU7iScyRiFTUthhX%2FusD5M1j42d4bLJjBrHgUVlc1L1Ui5QIFDyVc1xk%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}", "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}", "server": "cloudflare"} }, source: None }', src/services/account.rs:54:10

**Comment by tmarkovski** [comment]
Can't repro. Looks like it was fixed with prod deployment.
