### ISSUE TITLE
Node ecosystem support

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#274]

**Comment by fundthmcalculus** [comment]
@tmarkovski @MichaelEdwardBlack is this done and/or does one of you have the bandwidth to do it?

**Comment by tmarkovski** [comment]
This just says "Node". What is it in reference to?

**Comment by fundthmcalculus** [comment]
Ecosystem support. See the ticket that tracks this one.

**Comment by tmarkovski** [comment]
Ah, thanks. Checking from phone, didn't show the linked issue. I'll be owning that.
