### ISSUE TITLE
Term issue with colors in CLI and Windows

### ISSUE THREAD

**Issue by tmarkovski** [Dentity-Development/dentity-ecosystems-sdk#279]
Colors don't seem to render correctly in CMD and PS on Windows.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/1280118/145831702-b2f2dd04-b2c5-4b0f-9c55-a077e47895c5.png">

**Comment by fundthmcalculus** [comment]
`cmd` doesn't respect coloring, so that's not a bug. PS does things in weird ways. Let me check the windows terminal...

**Comment by fundthmcalculus** [comment]
![image](https://user-images.githubusercontent.com/16713623/146822420-ed432a34-0c7b-447c-85f8-50fcbce65e77.png)
Works in windows terminal as is.
