### ISSUE TITLE
Web Wallet Reference App

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#280]
a sample wallet reference app that helps me understand how credential issuance, acceptance, presentation, and verification work. 

In addition, a reference implementation of UIs to manage templates and trust registries.

the goal is to demonstrate functionality not a polished UI right now

**Comment by fundthmcalculus** [comment]
https://github.com/trinsic-id/sdk/issues/247

**Comment by fundthmcalculus** [comment]
https://github.com/trinsic-id/sdk-examples/pull/30 will close this issue, right @MichaelEdwardBlack ?

**Comment by tmarkovski** [comment]
Ping @MichaelEdwardBlack @michaeldboyd

**Comment by michaeldboyd** [comment]
Closing based on the PR above
