### ISSUE TITLE
publish "go/v1.2.0" tag for go users

### ISSUE THREAD

**Issue by dududko** [Dentity-Development/dentity-ecosystems-sdk#281]
Because `go.mod` is not located in the root of the repo I can not refer to a specific release of `trinsic-id/sdk`.
```
➜ go get github.com/trinsic-id/sdk/go@v1.2.0
go get: module github.com/trinsic-id/sdk@v1.2.0 found, but does not contain package github.com/trinsic-id/sdk/go
```

For this case there is a specific requirement for naming, in your case there should be a tag `go/v1.2.0`.
Without this tag it is only possible to refer to a specific commit.

**Comment by dududko** [comment]
The same applies to [okapi](https://github.com/trinsic-id/okapi)

**Comment by tmarkovski** [comment]
Thanks for pointing this our @dududko. I've tagged the last version with the correct tag name for go. I'm not sure if we have any changes between the `go/v1.2.0` and latest main, but we should be publishing a `1.3.0` version soon. Let me know if this works.

@fundthmcalculus let's add an action to tag a go formatted tag upon releases, so we can keep that automated.

**Comment by fundthmcalculus** [comment]
See #282  as the general case of this ticket.
https://github.com/trinsic-id/okapi/issues/315 <- for Okapi
