### ISSUE TITLE
Generate QR code format of credential

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#359]
Probably a local/edge-only situation, but it would be good to generate a QR code of the credential on the local device in case there isn't an internet connection. Probably would zip-compress and base-64 encode the credential before generating the QR code for display.

This might not be feasible due to the size of the QR code, but for short proofs, this could work.

Languages:
- [ ] .NET (Xamarin?)
- [ ] Go
- [ ] Java (android)
- [ ] Node (react?)
- [ ] Python
- [ ] Ruby
- [ ] Swift (iOS)
- [ ] Web (react?)

**Comment by tmarkovski** [comment]
There's few efforts in the community to introduce QR codes in the credential exchange. One we have implemented in v1 already. The challenge often comes down to proofs being too large or requiring interaction.

https://identity.foundation/didcomm-messaging/spec/#url-qr-codes

Re: proof size, we have implemented dynamic QR codes in the past that can accommodate few MBs of data, but we didn't create a spec out of this. Interesting discussions to be had.

**Comment by fundthmcalculus** [comment]
All good points. For the android demo, I might just throw something together using existing QR code generators. I debate on if this should be a server-generated action (yay consistency) or a device-generated action (yay locality). Maybe some of each?

**Comment by tmarkovski** [comment]
> All good points. For the android demo, I might just throw something together using existing QR code generators. I debate on if this should be a server-generated action (yay consistency) or a device-generated action (yay locality). Maybe some of each?

Server generated options aren't usable in offline scenarios, which frequently comes up in conversations when talking mobile use cases. If you can do it on the SDK, I would suggest client side generation, especially since it seems is temporary (non-standardized) solution.

**Comment by fundthmcalculus** [comment]
> Server generated options aren't usable in offline scenarios, which frequently comes up in conversations when talking mobile use cases. If you can do it on the SDK, I would suggest client side generation, especially since it seems is temporary (non-standardized) solution.

Agreed. Let's do it mobile side, since that's really the use case. We could eventually do a server-side version for websites to generate for scanning? Eg at the airline kiosk where you can be sure you have internet. I'm going to set up a separate set of .jar files for android that are mobile only so that the standard sdk jar remains compatible with server side Java as well.

**Comment by fundthmcalculus** [comment]
We also need to support NFC/BLE credential exchange. Correct, @michaeldboyd ?

**Comment by tmarkovski** [comment]
This work should align with community efforts regarding this problem and follow some of the standards established.

**Comment by janpieterz** [comment]
We'll move this to our internal roadmap for tracking.
