### ISSUE TITLE
Build passwordless login example application for Trinsic v1

### ISSUE THREAD

**Issue by lucasamonrc** [Dentity-Development/dentity-ecosystems-sdk#366]
Build a simple app showcasing a passwordless login flow using Trinsic v1.

Frameworks:
- [ ] Remix.run
- [x] Next.js

**Comment by fundthmcalculus** [comment]
@lucasamonrc  are you working on this? If so, I'll move it back to `In Progress`.

**Comment by lucasamonrc** [comment]
Still working on it, but it is not a huge priority right now. I might actually wait until we release v2.0 before I continue.

**Comment by lucasamonrc** [comment]
In my free time I finished it for v1.0 using Next.js. If you want to check out: https://github.com/lucasamonrc/ssi-login

**Comment by fundthmcalculus** [comment]
Slick, thanks!
