### ISSUE TITLE
Publish update to homebrew

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#374]
The homebrew package needs to be updated. It was last released December 2nd. Along with v1.3, we need to publish a new version of our CLI
- https://github.com/trinsic-id/sdk/deployments/activity_log?environment=homebrew

**Comment by tmarkovski** [comment]
This is planned with the 1.3 release, which we haven't done yet. @fundthmcalculus ?

**Comment by fundthmcalculus** [comment]
Correct, it hasn't been pushed yet.
