### ISSUE TITLE
Build Documentation github action is failing

### ISSUE THREAD

**Issue by tmarkovski** [Dentity-Development/dentity-ecosystems-sdk#39]
**Describe the bug**
Build Documentation github actions is failing

**To Reproduce**
See https://github.com/trinsic-id/sdk/actions/workflows/docs.yml

**Expected behavior**
Deploy docs successfully

**Comment by tmarkovski** [comment]
Fixed by removing the branch. @michaeldboyd please re-add the CNAME file with a PR against `main`. I forgot to write down the value

**Comment by michaeldboyd** [comment]
Closed with #42
