### ISSUE TITLE
Move SDK sample code to being injected

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#397]
We should not have sample application code embedded directly in the documentation. Instead, we should have a folder called `samples` which we can then code inject. This will help ensure the documentation and the codebase do not go out of sync with each other.

**Comment by fundthmcalculus** [comment]
@MichaelEdwardBlack need any help on this issue?

**Comment by MichaelEdwardBlack** [comment]
@fundthmcalculus I think I should be good on this. I believe most of it has been resolved. There are just a few things here and there that I'll get as I update to 1.4

**Comment by fundthmcalculus** [comment]
I'll close this issue then.
