### ISSUE TITLE
Code tabs on documentation are not getting formatted correctly

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#399]
This is what I see here: https://docs-v2.trinsic.id/walkthroughs/vaccination/

<img width="824" alt="image" src="https://user-images.githubusercontent.com/22651660/150868869-94fc7b6e-de5d-458a-93ce-a9c6a093cf3e.png">

**Comment by fundthmcalculus** [comment]
Reproduced on website via my machine. Does not reproduce when I run `mkdocs serve` locally. Investigating...

**Comment by fundthmcalculus** [comment]
<img width="1552" alt="Screen Shot 2022-01-25 at 9 06 17 AM" src="https://user-images.githubusercontent.com/16713623/150991941-04c390fc-9ded-4de2-827c-ebd29848e741.png">
Confirmed fix!
