### ISSUE TITLE
Update Reference Docs

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#408]
For each endpoint call, document the following things:
 ### Description
Ideally coming from the proto file, this description should include a high level explanation of the functionality
How might we import this content directly from the proto file's service? 

### Request and Response Data Models
- Links to the data models for the request and response bodies should be included. Just the links to the data models are needed within the reference markdown file, not the full tables of the data models - but that would be cool.

### Language specific code samples
Lower prio, as we write tests in each language we should include these test samples here within the docs. 
Good work for an onboarding contributor. 

### Coverage
- [x] #515
- [x] #518
- [x] #517
- [x] #516
- [x] #519
- [x] #520

**Comment by fundthmcalculus** [comment]
There is markdown doc link injection available in the Python reference section of the SDK. You should be able to reapply it from here: https://github.com/trinsic-id/sdk/blob/main/python/trinsic/services.py#L107

**Comment by michaeldboyd** [comment]
@lucasamonrc what is our coverage status here?

**Comment by lucasamonrc** [comment]
## Coverage Status

### Account Service
- [x] Construct Instance
    - [x] CLI
    - [x] TS
    - [x] C#
    - [x] Python
    - [x] Go
    - [x] Java
    - [x] Ruby 
- [x] Sign In
    - [x] CLI
    - [x] TS
    - [x] C#
    - [x] Python
    - [x] Go
    - [x] Java
    - [x] Ruby 
- [x] Get Account Info
    - [x] CLI
    - [x] TS
    - [x] C#
    - [x] Python
    - [x] Go
    - [x] Java
    - [x] Ruby 
- [x] Protect Account Profile
    - [x] CLI
    - [x] TS
    - [x] C#
    - [x] Python
    - [x] Go
    - [x] Java
    - [x] Ruby 
- [x] Unprotect Account Profile
    - [x] CLI
    - [x] TS
    - [x] C#
    - [x] Python
    - [x] Go
    - [x] Java
    - [x] Ruby

### Wallet Service
- [x] Create Wallet**
    - [x] Create wallet directly
    - [x] Create wallet with provider invitation
- [x] Insert item
- [x] Search / Query
    - [x] Basic Search
    - [x] SQL Search

### Provider Service
- [x] Issue Credential
    - [x] CLI
    - [x] TS
    - [x] C#
    - [x] Python
- [ ] Issue Credential from Template
- [ ] Check Revocation Status
- [ ] Update Revocation Status
- [x] Create Proof
    - [x] CLI
    - [x] TS
    - [x] C#
    - [x] Python
- [x] Verify Proof
    - [x] CLI
    - [x] TS
    - [x] C#
    - [x] Python
- [x] Exchange Credentials
    - [x] CLI
    - [x] TS
    - [x] C#
    - [x] Python
    - [x] Go
    - [x] Java
    - [x] Ruby
    - [x] Swift

### Provider Service
- [x] Invite Participant
    - [x] CLI
    - [x] TS
    - [x] C#
    - [x] Python
- [x] Check Invitation Status
    - [x] CLI
    - [x] TS
    - [x] C#
    - [x] Python
- [ ] Create Ecosystem
- [ ] List Ecosystems
- [ ] Accept Invite

### Trust Registry
- [ ] Create a Ecosystem Governance Framework
    - [x] CLI
    - [ ] TS
    - [ ] C#
    - [ ] Python
    - [ ] Go
    - [ ] Java
    - [ ] Ruby
- [ ] Register Issuers and Verifiers
    - [x] CLI
    - [ ] TS
    - [ ] C#
    - [ ] Python
    - [ ] Go
    - [ ] Java
    - [ ] Ruby
- [ ] Unregister Issuers and Verifiers
    - [x] CLI
    - [ ] TS
    - [ ] C#
    - [ ] Python
    - [ ] Go
    - [ ] Java
    - [ ] Ruby
- [ ] Check Authoritative Status
    - [x] CLI
    - [ ] TS
    - [ ] C#
    - [ ] Python
    - [ ] Go
    - [ ] Java
    - [ ] Ruby
- [ ] Search
    - [x] CLI
    - [ ] TS
    - [ ] C#
    - [ ] Python
    - [ ] Go
    - [ ] Java
    - [ ] Ruby
- [ ] Cache Offline Registry File 
    - [x] CLI
    - [ ] TS
    - [ ] C#
    - [ ] Python
    - [ ] Go
    - [ ] Java
    - [ ] Ruby

**Comment by lucasamonrc** [comment]
@michaeldboyd This issue should be ready to be closed, especially because more detailed improvements on the documentation are being tracker in issue #589 and #606
