### ISSUE TITLE
Write generalized unit tests in TypeScript for all our SDK service calls

### ISSUE THREAD

**Issue by lucasamonrc** [Dentity-Development/dentity-ecosystems-sdk#412]

**Comment by fundthmcalculus** [comment]
@lucasamonrc can you elaborate on this?

**Comment by lucasamonrc** [comment]
> @lucasamonrc can you elaborate on this?

I think @michaeldboyd will do a better job elaborating actually.

**Comment by tmarkovski** [comment]
Another call for elaboration please? @michaeldboyd 
Otherwise, we'll have to close this issue.

**Comment by lucasamonrc** [comment]
This issue is actually related to issue #408. @michaeldboyd recommended that it would be useful to write generalized tests for our node sdk in typescript that then could be referenced as snippets for our v2 reference docs.

Did I understand it correctly @michaeldboyd?

**Comment by michaeldboyd** [comment]
We currently have a unit test for the vaccination demos in each language that we import. We don't have any unit tests that to demonstrate reference SDK calls on our SDK Services reference page. I don't think we need unit tests covering all languages at this point, but having just one will be helpful for developers to get an idea on what SDK calls look like when they're reviewing docs for the first time. Having comprehensive coverage of all our sdk calls in at least one language will also help us know if something changes.

**Comment by fundthmcalculus** [comment]
> We currently have a unit test for the vaccination demos in each language that we import. We don't have any unit tests that to demonstrate reference SDK calls on our SDK Services reference page. I don't think we need unit tests covering all languages at this point, but having just one will be helpful for developers to get an idea on what SDK calls look like when they're reviewing docs for the first time. Having comprehensive coverage of all our sdk calls in at least one language will also help us know if something changes.

That's part of some of the broader initiatives I'm doing around complete SDK test coverage to verify behavior in all languages. (No edge cases). I don't really unit test the SDKs, so much as integration test them, since unit-of-behavior is the full-stack call. If there are other developments on this, keep me in the loop.
