### ISSUE TITLE
Move SDK node tests entirely to typescript

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#416]
Eliminate all the commonjs tests, replace with typescript. Relates to #412

**Comment by fundthmcalculus** [comment]
@tmarkovski @MichaelEdwardBlack is there any opposition to using a test harness other than ava? In my testing, getting ava to support typescript cleanly is kind of a pain. I'd vote to use something like Jest, which automatically integrates with babel for the typescript transpilation. Similar to here: https://github.com/fundthmcalculus/blake3-ts/blob/main/package.json

**Comment by tmarkovski** [comment]
Not opposed to using different harness, Ava was just a choice. I do however think Ava supports Typescript very cleanly, by adding the "ts" extension in `package.json` and running `ava` normally. We do this in the template microservice https://github.com/trinsic-id/server/blob/2dc20e597cb3cdfbb126741e251ec86de05adfd6/template-service/package.json#L37
For browsers, I think the situation is different, but we don't use Ava there. I think it's challenging to setup TS as well.

**Comment by fundthmcalculus** [comment]
That's the cleanest example of ava TS I've seen, thanks for the link! I'll see what I can do to keep ava for both. I'd rather not have different test harnesses for node and browser if I can avoid it.
