### ISSUE TITLE
Create Replits for each SDK

### ISSUE THREAD

**Issue by MichaelEdwardBlack** [Dentity-Development/dentity-ecosystems-sdk#421]
- [ ] Web
- [ ]  ~ iOS ~ not supported: https://replit.com/talk/ask/Can-we-make-iOS-or-Android-apps-using-replit/52724
- [ ]  ~ Android ~ not supported: https://replit.com/talk/ask/Android-Studio/7302
- [ ]  Node
- [ ]  Dotnet
- [ ]  Go
- [ ]  Java
- [ ]  Python

Aiming to finish this task by Feb 11th

**Comment by fundthmcalculus** [comment]
Just FYI, there is an issue template for per-language SDK change requests.
Also, can iOS and android be repl.it, I don't think so.

**Comment by tmarkovski** [comment]
Closing this issue as needs have changed.
