### ISSUE TITLE
Structure and publish the walkthrough for each platform use case

### ISSUE THREAD

**Issue by MichaelEdwardBlack** [Dentity-Development/dentity-ecosystems-sdk#422]
Go through each sdk (especially higher demand sdk's like web, ios, and android) and go through the walkthrough's (or make them). With each walkthrough add steps to overcome issues that someone could run into (or that I run into).

- [x] Web
- [x] Node
- [x] Dotnet
- [x] Go
- [x] Java
- [x] Python

**Comment by fundthmcalculus** [comment]
@MichaelEdwardBlack  any updates on this?

**Comment by michaeldboyd** [comment]
Do issuers need a wallet? some don't and they provide issuance only.

**Comment by MichaelEdwardBlack** [comment]
Some don't but as of now when you create an account you're also creating a wallet so it just comes by default.

**Comment by michaeldboyd** [comment]
- [x] Add ecosystem steps to quickstarts (either through seed data or ad hoc ecosystem)
