### ISSUE TITLE
Package Consumption Testing Against Prod

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#425]
As a failsafe to catch unintended behavior, as well as to ensure that the documentation code samples remain consistent with the state of the server. We need to do the following nightly (or some other schedule that is *independent of server deployments*):
1. Download and install latest packages
2. Compile/build/run the samples
3. Assert expected behavior
4. Fail exit if necessary

This isn't a true integration test as much as a confirmation of some basic behavior. The integration tests to catch state issues reside in the sdk tests themselves. A reasonable argument could be made that this issue should be in the `sdk-examples` repository. Unless github actions has a fleet of remote mobile test devices, there isn't really a good way to do the mobile side testing. The objective here is to catch data/api contract changes with the server as they get deployed, not to ensure functionality on every environment we support (a testing matrix too large to be practical).

Languages:
- [x] .NET
- [x] Go - https://github.com/trinsic-id/sdk/pull/683
- [x] Java
- [x] Python - https://github.com/trinsic-id/sdk/pull/530
- [x] Ruby - https://github.com/trinsic-id/sdk/pull/532
- [x] Swift @fundthmcalculus 
- [x] Web @MichaelEdwardBlack 
- [x] Use authenticated github token to bypass API limits. (a common cause of failures) - also spread the actions over a 10 minute window to reduce max API call rate.

**Comment by michaeldboyd** [comment]
Also discuss: how testing works w/re to our different ci/cd environments

**Comment by fundthmcalculus** [comment]
> Also discuss: how testing works w/re to our different ci/cd environments

Off topic for this ticket. We already cover testing in our CI pipeline (we don't have a CD pipeline). Currently, everything in CI points to `staging`, while locally most of us work against `dev`. We could change this with a github secret (being used as an environment variable).

**Comment by tmarkovski** [comment]
Yes, we switched CI testing between Staging and Dev with almost no issues during this last deployment and it worked well. We can easily parametrize the actions to repoint to Prod as well.
I do, however, feel that production testing should be done using the production packages instead, and not directly run the SDK integration tests.

**Comment by fundthmcalculus** [comment]
That was my point with this ticket. Hence the parameterized ci pipeline being off topic.
