### ISSUE TITLE
Python SDK

### ISSUE THREAD

**Issue by tmarkovski** [Dentity-Development/dentity-ecosystems-sdk#44]
## Objective

Expand support of Okapi and Trinsic SDK for Python.

## Solution

This port should leverage the [Okapi](https://github.com/trinsic-id/okapi) stack and  [gRPC tools for Python](https://grpc.io/docs/languages/python/basics/) as the foundation of the library. The effort required can be roughly separated in two phases:

- Python support for Okapi
- Python support for Trinsic SDK

The library should follow naming guidelines established by existing libraries, but in a way that's idiomatic to Python. 

## Tracking Effort

- [x] Python wrapper for Okapi - this wrapper should deliver functionality that will allow Okapi to be used in Python on any platform. Initial work has been started using the old library name "didcomm-grpc". Okapi uses Protobuf as data contract for the the FFI layer, but does not use any gRPC functionality. This library will invoke existing native library built in Rust.
  - [x] Basic Unit tests - generate key, sign message, etc. https://github.com/trinsic-id/okapi/pull/50
  - [x] Build Pipeline - provide GH action that builds and run the tests https://github.com/trinsic-id/okapi/pull/53
  - [x] Package Publishing - GH action that publishes packages to PyPI. This action should be a separate job in the exist build pipeline. It should trigger from a `release` event (already setup) and use the build native libraries (windows, linux, macos) to provide support for all platforms
- [x] Trinsic SDK - leverages Okapi as main dependency and builds support for profile management and gRPC service invocation.
  - [x]  Basic unit tests - these tests should be runnable manually against a running ecosystem stack. Currently, we run the locally against `localhost`, but soon we will be able to run the tests as part of CI. For this purpose, tests should be parametrized and accept Ecosystem Server URL.
  - [x] Build Pipeline - provide GH action that builds and run the tests
  - [x] Package Publishing - GH action that publishes packages to PyPI. 
- [x] Release github action to deploy to PyPI.

**Comment by michaeldboyd** [comment]
Link to feature: https://trinsicproduct.productboard.com/feature-board/planning/features/8301485

**Comment by fundthmcalculus** [comment]
Couple thoughts:
1. Do we have an API/schema definition that is independent of the core libraries? (https://github.com/trinsic-id/sdk/tree/main/proto)

2. Do we have / plan to have a coordinated release of the packages wrt api versions?

**Comment by tmarkovski** [comment]
1. Not really. Most of our SDK (for now) has simple inputs (string, JSON). However, some SDK endpoints use the proto schema directly, like `WalletProfile` and we haven't abstracted this. We may want to at some point. For now, we're just gathering experience before we make a decision on what makes practical sense.

2. We do not have plan for this, but we should come up with one. Tagging @StevenTCramer . I think the best way to achieve this would be to coordinate the SDK version with a version of the Infrastructure Stack. Our API is essentially the state of the Stack. That said, being able to somehow associate major SDK version with stack version deployments, would be highly desirable. Open to any ideas here.

**Comment by fundthmcalculus** [comment]
Question in to the `python-betterproto` developers: https://github.com/danielgtaylor/python-betterproto/issues/252
Demo package: https://test.pypi.org/project/trinsic-okapi/

**Comment by fundthmcalculus** [comment]
SDK package: https://test.pypi.org/project/trinsic-sdk/

**Comment by tmarkovski** [comment]
Can this issue be closed? Doesn't seem it has other tasks left. @fundthmcalculus ?
