### ISSUE TITLE
Improve error messages presented to users

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#445]
Given the errors we have, we need to ensure that we give the user useful, actionable error messages.
Several examples
* If the okapi binary can't be loaded, let the user know
* If the network fails to connect, let the user know

Languages:
- [x] .NET
- [x] Go
- [x] Java
- [x] Node
- [x] Python
- [x] Ruby
- [x] Swift
- [x] Web

**Comment by fundthmcalculus** [comment]
In light of no comments, I am going to assume that my listed objectives are sufficient at the SDK level. The server side error messages are a separate discussion.

**Comment by tmarkovski** [comment]
I think this is more of a general developer guidance, rather than direct actionable item. We did few improvements to ensure error messages are propagated to the client SDK consistently. If there are specific endpoints that require update, we can address them on a case by case basis.

**Comment by fundthmcalculus** [comment]
You are correct. There are a couple of points that need better error handling at the SDK level as noted above. I'll implement those.

**Comment by fundthmcalculus** [comment]
all dynamic languages log where they are looking for the native binary extensions. The compiled languages this is obviously not an issue. Identifying network connectivity issues was determined not to be a priority in https://github.com/trinsic-id/server/pull/420
