### ISSUE TITLE
Support Encoding `AccountProfile` as a base64 token string

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#454]
We need to support storing the `AccountProfile` as a token secret, and the most general method for that is a base64 string. We should serialize the `AccountProfile` to protobuf binary format, then base64 encode it. We don't use JSON serialization because injection into other environments is much more cumbersome. Please note that the base64 encoding is NOT encrypted.

Languages:
- [x] .NET
- [x] Go
- [x] Java
- [x] Node
- [x] Python
- [x] Ruby
- [x] Swift
- [x] Web

**Comment by tmarkovski** [comment]
Does this mean that the `SignIn` and `CreateEcosystem` endpoints in Account and Provider services in the SDK are changed to return a `string` instead?

**Comment by fundthmcalculus** [comment]
> Does this mean that the `SignIn` and `CreateEcosystem` endpoints in Account and Provider services in the SDK are changed to return a `string` instead?

I tend to say no, since that's just passing encoded data as opposed to the data itself. You can't `unprotect` the base64 data itself. I would generally want to put an extension method on `AccountProfile` called `ToBase64String()` and `FromBase64String()`. How/where the user loads the base64 string is irrelevant, but allowing them to import/export it is useful (JSON storage, env var storage, etc)

This would be a set of functions available everywhere, further convenience methods could be more platform/language specific.
