### ISSUE TITLE
Utilize okapi-based blake3 hashing

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#456]
A couple languages are using separate blake3 hashing packages, switch these to the native okapi binaries for performance and consistency. Also verify that we send the full 256 bytes of oberon proof in the grpc metadata

Languages:
- [x] .NET
- [x] Go
- [x] Java
- [x] Node #470
- [x] Python
- [x] Ruby
- [x] Swift https://github.com/trinsic-id/sdk-swift/pull/10
- [x] Web #470

**Comment by tmarkovski** [comment]
This seems complete now

**Comment by fundthmcalculus** [comment]
It is, closing.
