### ISSUE TITLE
Proposed Golang SDK Updates

### ISSUE THREAD

**Issue by sethjback** [Dentity-Development/dentity-ecosystems-sdk#474]
### Purpose

The goal of this issue is to open a discussion around a couple of consistency / housekeeping items for the golang codebase.

#### Private Base Implementations

Currently ever service is defined in an interface and then a base implementation is provided. Those base implementations are not commented in the standard way for godoc to build documentation and thus tools like `golint` are complaining and ultimately failing.

It is a pattern to keep the base implementations of interfaces private (unexported) thus not requiring the same level of documentation.

The question to be resolved:

Is there a reason to have the base implementations exported? If not they can be made private and there is no further work required. If yes, we need to comment the code base appropriately.

#### Function Call Arguments

Currently we have a mix of passing in the Server API request struct directly and passing in fields that then get validated and an api request is built from them.

grpc request struct:

```golang
func (c *CredentialBase) CheckStatus(userContext context.Context, request *sdk.CheckStatusRequest)
``` 

request fields:

```golang
func (c *CredentialBase) VerifyProof(userContext context.Context, proofDocument Document)
``` 

Either way has it's pros/cons, we just need to be consistent.

#### Unit vs. Integration testing

Currently there is a mix of unit and integration tests in the test files. I would like to propose we keep the tests in the `_test` files to unit tests and things we can mock, and have a separate process in place for doing full blow integration testing against a deployed environment.

**Comment by tmarkovski** [comment]
Service Base implementations can be made internal to the SDK where the language permits that. We don't intend the users to implement them or construct them directly. They're abstract where appropriate.

Definitely moving towards just exposing the actual `Request` and returning `Response` directly in the APIs and moving away from individual parameters. This makes all calls consistent and forces us to maintain both clean and well-documented `Request` objects to guide users. I may have missed to update this in few places, but that's the intention.

Considering the SDKs are really just wrappers around the actual gRPC endpoints with the added custom metadata generation, this turns most SDK calls into integration tests.
Unit tests seem to boil down to testing oberon header generation, token protections, and few others. I agree on the approach that we should test both.

**Comment by sethjback** [comment]
> Considering the SDKs are really just wrappers around the actual gRPC endpoints with the added custom metadata generation, this turns most SDK calls into integration tests.

That is true. There are a few things we can wrap in unit tests, and we could mock the API to make sure the contracts are respected.

My main goal is wanting to be able to run `go test` and have it return fairly quickly with all the internal code checks done, then plan for and run the integration tests. Currently there is a mix of both.

**Comment by fundthmcalculus** [comment]
> > Considering the SDKs are really just wrappers around the actual gRPC endpoints with the added custom metadata generation, this turns most SDK calls into integration tests.
> 
> That is true. There are a few things we can wrap in unit tests, and we could mock the API to make sure the contracts are respected.
> 
> My main goal is wanting to be able to run `go test` and have it return fairly quickly with all the internal code checks done, then plan for and run the integration tests. Currently there is a mix of both.

In general, I have intentionally constructed the SDK "unit tests" as integration tests. This is to ensure api behavior, since we are such a thin wrapper. This also allows us to do some of the server integration tests in a public manner, eg, call sequence bugs that customers (Roman Levin) have reported.

**Comment by fundthmcalculus** [comment]
With respect to the mix-and-match of ` CallResponse ServiceCall(CallRequest request)` and other things, that is simply because I haven't prioritized making those all consistent until the API stabilizes a little more. I wouldn't worry about that for now, let's do that once 1.4 is released. I'm fine with compilation level breaking changes in 1.5, provided behavior doesn't also change.

**Comment by sethjback** [comment]
There really aren't that many - I just wanted to make sure to do it the way all the other SDKs were going to

**Comment by fundthmcalculus** [comment]
> There really aren't that many - I just wanted to make sure to do it the way all the other SDKs were going to

I have a backlog ticket for that. will do shortly: https://github.com/trinsic-id/sdk/issues/479
