### ISSUE TITLE
Node sdk does not get built before publishing to npm

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#48]
**Describe the bug**
npm sdk not building before getting released to npm.

**To Reproduce**
1. `mkdir test-npm && cd test-npm; npm init && npm i @trinsic/trinsic`
2. add `const trinsic = require('@trinsic/trinsic');` to the top of the `index.js`
3. `npm run`
notice how the module does not get imported. Inspecting the node_module shows that there is no ./dist directory
![image](https://user-images.githubusercontent.com/22651660/122336429-b68bfd80-cef1-11eb-82ba-27b211f5b238.png)

**Expected behavior**
build before publishing. successfully import
**SDK (or CLI) you are using**
 - SDK: node
 - 
**Additional context**
Add any other context about the problem here or remove this section

**Comment by tmarkovski** [comment]
The issue was in the publishing GH action. Libs are correctly generated - https://github.com/trinsic-id/sdk/actions/runs/946477814.
This should be resolved with #49
