### ISSUE TITLE
Credential template tests

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#481]

**Comment by fundthmcalculus** [comment]
Can you elaborate further?

**Comment by fundthmcalculus** [comment]
We have credential template tests in some languages such as go: https://github.com/trinsic-id/sdk/blob/main/go/services/services_test.go#L316-L381

**Comment by tmarkovski** [comment]
.NET https://github.com/trinsic-id/sdk/blob/b7cb49edf648960b03867e17fe249fa1a52db4ff/dotnet/Tests/Tests.cs#L274
Node https://github.com/trinsic-id/sdk/blob/b7cb49edf648960b03867e17fe249fa1a52db4ff/node/test/WalletService.ts#L74
Web https://github.com/trinsic-id/sdk/blob/b7cb49edf648960b03867e17fe249fa1a52db4ff/web/test/WalletService.test.js#L85
Swift https://github.com/trinsic-id/sdk-swift/blob/main/Tests/TrinsicTests/TemplateTests.swift
