### ISSUE TITLE
Add intercom to mkdocs

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#484]
To help readers more easily ask clarifying questions, we can add our intercom plugin to our documentation site. 

This can be done in a similar way to how mkdocs recommends adding a comments section: https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/#giscus-integration

Create the embed script within the intercom portal and then add it to our documentation so that it shows up on one of the bottom corners of the page.

If it conflicts with any other UI components, move either the plugin around or the other components so that readers won't get frustrated with the plugin covering up important material. 

Ping @michaeldboyd if you need access to the intercom portal.

**Comment by geel9** [comment]
Thoughts on doing this before GA?

@michaeldboyd @janpieterz

**Comment by janpieterz** [comment]
In my opinion not a requirement, I'd say move to Sprint 8 and tackle when everything in Sprint 7 is done?

**Comment by geel9** [comment]
@janpieterz I can take this on whenever.

I imagine that the actual engineering work for this issue is going to be extremely minimal -- probably just copy/pasting a <script> tag -- but the actual organizational work to prepare for customers to be asking questions on our v2 docs page extends far beyond solely my reach.

**Comment by janpieterz** [comment]
Yes, I would say add the bubble whenever this pops up after current sprint work (I think we're close, but you could potentially help with some IDOR reviews?). We can then focus on the documentation knowledge base area etc. between basecamp and marketing go-live.

**Comment by janpieterz** [comment]
@chiarapaskulin Looks like this was completed last sprint, right? Closed it and moved to done, awesome work :)
