### ISSUE TITLE
Improve package readme pages

### ISSUE THREAD

**Issue by tmarkovski** [Dentity-Development/dentity-ecosystems-sdk#494]
Add better user facing information to our README pages that show up in package manager web sites, such as https://www.npmjs.com/package/@trinsic/trinsic-web and https://www.nuget.org/packages/Trinsic/

Languages:
- [x] .NET https://github.com/trinsic-id/sdk/pull/539
- [x] ~Go~ (source code direct)
- [x] ~Java~ (no central repo)
- [x] Node https://github.com/trinsic-id/sdk/pull/539
- [x] Python https://github.com/trinsic-id/sdk/pull/538
- [x] Ruby https://github.com/trinsic-id/sdk/pull/539
- [x] ~Swift~ (source code direct)
- [x] Web https://github.com/trinsic-id/sdk/pull/539

**Comment by fundthmcalculus** [comment]
Is this specific to node, or a general problem? I have descriptive `README.md` for Python, Java, and Ruby already.

**Comment by tmarkovski** [comment]
Pretty much all package landing pages are empty and/or not very descriptive

https://rubygems.org/gems/trinsic-services
https://pypi.org/project/trinsic-sdk/
https://www.nuget.org/packages/Trinsic/

**Comment by fundthmcalculus** [comment]
I added the SDK change template so we can track across languages.

**Comment by tmarkovski** [comment]
@michaeldboyd Tagging you, as this has sdk/product promotional character and can reuse cross-link to documentation

**Comment by fundthmcalculus** [comment]
@MichaelEdwardBlack if you'd like to dig into all the package README injection with me, just let me know. :)

**Comment by MichaelEdwardBlack** [comment]
Yes I can at least jump in on the node and web READMEs @fundthmcalculus

**Comment by michaeldboyd** [comment]
#422 will address any additional language specific quickstarts, including the readme content within the package repositories
