### ISSUE TITLE
Check for valid auth token post `AccountService.Unprotect()`

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#501]
* Carried over from: https://github.com/trinsic-id/sdk/issues/460 as a subtopic
### Need to Answer
1. How do we verify the token is properly unprotected? (currently, if you unprotect with the wrong token code, it still "succeeds")
2. Should we automatically verify this?

### Background
See this ticket and comment: https://github.com/trinsic-id/sdk/issues/460#issuecomment-1062881136

**Comment by tmarkovski** [comment]
My suggestion:
Create another SDK method that should be called post `SignIn` (SignInConfirm, SignInFinalize, etc) that will do the following:

- Fetch the server PK used for signing
- Unblind the token
- Build a proof with a fixed nonce and payload
- Verify the token

Additionally, to prevent brute force guess of this blinding code, we should implement a KDF that will transform the code before using it. This is a bonus security change and will require addition to libokapi.

**Comment by fundthmcalculus** [comment]
Alright, let's make this happen. Would it be possible to do this API endpoint concurrently with the KDF work inside Okapi? I'd like to get these changes into 1.6 if possible. What are your thoughts?

**Comment by fundthmcalculus** [comment]
This is done with the new login flow already.
