### ISSUE TITLE
building docs site fails

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#537]
This seems to be related to an updated version of mkdocs and mkdocs-material.
Example run: https://github.com/trinsic-id/sdk/runs/5818606195?check_suite_focus=true

**Comment by squidfunk** [comment]
Maintainer of Material for MkDocs here 🙋‍♂️

This error was just fixed on `master`, so if you restart the build, it should be fine. It was the result of a small refactoring I did some days ago and occurred when a link was used inside a headline:

```
# Headline [Link](#)
```

**Comment by fundthmcalculus** [comment]
wow, thanks @squidfunk !
