### ISSUE TITLE
Make docs authenticated to beta users

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#54]
https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad

Both our internal and external docs can be hosted on azure using their new static web apps option. this will give us:
- staging sites that build on PRs
- invitation only access with different identity providers

**Comment by tmarkovski** [comment]
@michaeldboyd Closing this, as it no longer seems relevant. Please re-open if needed.
