### ISSUE TITLE
Trying to create an ecosystem using the CLI fails

### ISSUE THREAD

**Issue by Franklin89** [Dentity-Development/dentity-ecosystems-sdk#544]
### Reproduction steps

I am using the CLI installed through `winget` on my windows machine to create a new ecosystem. This call fails with the following error message: 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SerializationError', src\services\config.rs:83:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The command that I am running is as follows:

```
trinsic provider create-ecosystem --email "matteo@farmerconnect.com"
```

No matter what I pass in for the options. If I leave all of them empty or fill them all with valid strings.

I have version 1.4.0 of the trinsic.cli installed:
```
Name                                     Id                                        Version             Available Source
-----------------------------------------------------------------------------------------------------------------------
trinsic                                  trinsic.cli                               1.4.0                         winget
```

**Comment by tmarkovski** [comment]
@Franklin89 Can you please try removing older configuration file that may be on your system. It will be located in `~/.trinsic/config.toml`

**Comment by Franklin89** [comment]
Thank you @tmarkovski :-D 

Works great now 👍
