### ISSUE TITLE
SDK Docs Author List incorrect on prod

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#552]
This is likely due to checkout history/depth issues, but the SDK author plugin is blaming @michaeldboyd for everything, which is inaccurate. There is a PR open in the upstream plugin for authors sorted by contribution and removing low-contribution count authors.
https://github.com/timvink/mkdocs-git-authors-plugin/pull/62

https://trinsic-id.slack.com/archives/C033TGL9UBU/p1649294031707749

**Comment by tmarkovski** [comment]
The other issue I observed is when I enabled `show_contribution` in the plugin setting, the % didn't show up - format remained the same. I was testing with local build and full checkout.

**Comment by fundthmcalculus** [comment]
Now with the fixed deployment, this is done.
https://docs-v2.trinsic.id/reference/services/credential-service/
