### ISSUE TITLE
Refactor SDK sample code injection into specific tests

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#572]
This is related to documentation, and needs to have code samples separated from some of the other tests. Ideally, it's on a per-file basis, so that the `*.md` files have a matching set of `*_sample.*` files.

@geel9 we need to have separate samples that can also be run as part of the unit tests, but they should be similar to the existing sample codes, wherein they are self contained `main()` functions with sequences of calls. Python is probably the best current example of this, wherein the sample code is called by the unit test harness directly.

Languages:
- [x] .NET
- [x] Go
- [x] Java
- [x] TypeScript
- [x] Python
- [x] Ruby
- [x] Swift

**Comment by fundthmcalculus** [comment]
This issue is related to the nested code samples issue:
https://github.com/trinsic-id/sdk/issues/620

**Comment by fundthmcalculus** [comment]
This also related to handling the production package testing: #530

**Comment by fundthmcalculus** [comment]
[Production Package Testing](https://github.com/trinsic-id/sdk/issues/425)

**Comment by geel9** [comment]
Would this already be largely resolved for Python (`vaccine_demo.py`) and TypeScript (`VaccineDemoShared.ts`)? Or does this extend beyond the vaccine walkthrough?

**Comment by fundthmcalculus** [comment]
It should be largely resolved with the corresponding file for the vaccine demo in each language.
