### ISSUE TITLE
SearchResponse Count is 0, although there are Items in the response

### ISSUE THREAD

**Issue by Franklin89** [Dentity-Development/dentity-ecosystems-sdk#583]
### Reproduction steps

1. Create a credential and insert it into a wallet
2. From the `WalletService` call `SearchAsync`
3. The `SearchResponse` has a property named `Count` which is `0` even though the Items list has 1 item.
4. `Items.Count` is equal to `1`

![image](https://user-images.githubusercontent.com/4151467/163955929-fc724fb5-e850-4f15-948e-dedbf6e099d2.png)

Could it be that the `Count` on the `SearchResponse` references a different count? In that case it is a bit ambigious IMHO.

**Comment by fundthmcalculus** [comment]
> Could it be that the Count on the SearchResponse references a different count? In that case it is a bit ambigious IMHO.

It shouldn't reference something else, so it's not misleading, but that would be a bug. I'm conflicted on if I care about returning the `count` when you can just ask the `List.Count` or `len(list)` or [language of your choice here] to get the number of elements in the collection.

**Comment by tmarkovski** [comment]
The intent for this field is to return the total number of elements in a query, as opposed to the current result set. The `HashMore` and `ContinuationToken` will have values, when the query has more elements then what it shown in the List.
This may not be possible using the current storage type. Let me investigate and get back on this.

**Comment by fundthmcalculus** [comment]
Short term investigation says the `.Count` parameter isn't currently being populated. If you need to stream more results, check the `.HasMore` parameter. Otherwise, you can get the item count from the the `.Items` collection directly, as you described.

**Comment by fundthmcalculus** [comment]
@Franklin89 the plan is to remove the `.Count` parameter, since the count of items returned is in the `.Items` collection. That being said, the backend will populate the `.ContinuationToken` and `.HasMore` properties if there are more items in the query than returned "over the wire".

**Comment by fundthmcalculus** [comment]
`.Count` parameter removed as part of #598

**Comment by Franklin89** [comment]
@fundthmcalculus FYI

I just used the `TemplateService` to check if an issuer has a certain template. When using that service the response is a bit different compared to the other search responses. It also has the `.Count` parameter which is also set and then instead of an `Items` collection it just has an `ItemsJson`.

**Comment by fundthmcalculus** [comment]
> @fundthmcalculus FYI
> 
> I just used the `TemplateService` to check if an issuer has a certain template. When using that service the response is a bit different compared to the other search responses. It also has the `.Count` parameter which is also set and then instead of an `Items` collection it just has an `ItemsJson`.

Good catch, thanks! I'll update this endpoint to behave more like the other, which is more in line with what we would expect. Thanks! @tmarkovski do you agree?
