### ISSUE TITLE
Documentation Improvements / Nitpicks

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#589]
- **Misc**
	- [x] Protobuf Type links are relative to current page, which doesn't work when injected
	- [x] Maybe alphabetize the order of the Service listings in sidebar?
- **SDK Reference**
	- **Account Service**
		- [x] Fix up documentation on `ServiceOptions` (capitalization / full description of message)
		- [x] Docs claim that a Sign In Request will return a full account profile, but they now return an opaque string.
		- [x] Provide an info box at top of page explaining that "Accounts" and "Wallets" are the same _entity/resource_, but operations on them are segmented between the two services.
		- [x] Provide an info box for what "Protecting" and "Unprotecting" an account really means
	- **Wallet Service**
		- [x] Create same infobox at top of page explaining the account/wallet distinction
		- [ ] Provide a schema for the SQL table that searches query against
		- [x] ~~Remove link to Cosmos DB (users don't need to know about our backend database, IMO)~~
		- [x] `apporach` -> `approach`
	- **Credential Service**
		- [ ] Explain what a "JSONLD frame" is and how to generate one to request a proof
	- **Template Service**
	- **Provider Service**
		- [x] `directly through them` -> `directly to them`
		- [x] Move the `Create Ecosystem` section to the top, as it must be performed before anything else can happen
		- [x] ~~Elaborate on Ecosystems~~
	- **Trust Registry Service**
		- [x] Fix verifier-related text and CLI samples referring to issuers
	- **Protocol Buffers**
		- [x] Remove in-page table of contents, as the sidebar already has a table of contents
		- [x] Add text at top of page providing some introductory information to _what_ is contained in this page

**Comment by fundthmcalculus** [comment]
@tmarkovski @sethjback can you answer this question: *Provide a schema for the SQL table that searches query against*? Thanks!

**Comment by tmarkovski** [comment]
Record schema is simple: id, type, and data. Data is any json object. Type is free string, up to the user to set it if they want.
Any schema builder can be used to generate a schema for this.

**Comment by fundthmcalculus** [comment]
> Record schema is simple: `id`, `type`, and `data`. `data` is any json object. `type` is free string, up to the user to set it if they want. Any schema builder can be used to generate a schema for this.

@geel9 there is the answer!
