### ISSUE TITLE
trinsic cli banner version displayed is incorrect

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#594]
### Reproduction steps

See attached photo
![image](https://user-images.githubusercontent.com/16713623/164359546-8e9cf5d9-c926-4dd7-8855-c38fb9106e35.png)

### Reproduction Code

```bash
winget install trinsic.cli
trinsic
```
on windows

**Comment by tmarkovski** [comment]
Might be fixed already with https://github.com/trinsic-id/sdk/pull/510

**Comment by fundthmcalculus** [comment]
> Might be fixed already with #510

Making a patch release 1.4.1 to see if this is the case.

**Comment by fundthmcalculus** [comment]
This is fixed already as mentioned by @tmarkovski . Closing this issue.
