### ISSUE TITLE
Convert node/typescript to `async` `await` form from `Promise` structure

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#596]
We need to use either `async` and `await`, or `Promise` only. Not both. Error handling with `try` `catch` doesn't work across `Promise` structures, unfortunately. Moving completely to `async` allows us to modernize the node packages more.

**Comment by tmarkovski** [comment]
I think the fact grpc tooling doesn't produce code with support for `Promise` forces us to use promise callbacks in our implementation.
Note that this only affect the node stream. Browser tooling does produce Promise definitions and those can be fully async/await.
