### ISSUE TITLE
Docs Code Injection includes nested targeting blocks

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#617]
### Problem

When we inject code into our documentation using the `codeinclude` plugin, nested injection target comments are also included.

For example:

```csharp
// testSignInAndGetInfo() {
// accountServiceConstructor() {
var myAccountService = new AccountService(_options);
// }
// accountServiceSignIn() {
var myProfile = await myAccountService.SignInAsync(new());
// }
myAccountService.Options.AuthToken = myProfile;
// accountServiceGetInfo() {
var output = await myAccountService.GetInfoAsync();
// }
Assert.NotNull(output);
// }
```

When `testSigninAndGetInfo` is included, every nested targeting pair comment (`accountServiceConstructor() {` etc.) is also included, resulting in confusing code snippets.

<img src="https://user-images.githubusercontent.com/1294419/166486099-92d2044e-7125-4921-b89f-3e361d71e5f2.png" width="400"/>

### Possible Solutions

- Fork `mkdocs-codeinclude-plugin` and add stripping functionality; PR to main repo and unfork when merged
  - **Pros**
    - Cleanest solution; this is where the code for this should probably live
    - Less bespoke code on our end
  - **Cons**
    - We already have [an outstanding PR](https://github.com/rnorth/mkdocs-codeinclude-plugin/pull/26) since February that hasn't been merged yet. Will this also just be stuck in limbo?
      - Can just fork permanently if need be
    - Making it work for _everyone's_ injection target comment syntax is out of scope; we just need it to work for _ours_.
      - Our style is `// injectionTargetName() {` followed by `// }`. However, this exact syntax isn't necessary -- the plugin _only_ looks for a token (`injectionTargetName`) on any line, and then any pair of matching brackets which follows.
        - Another argument for forking permanently on our end
- Post-process externally to the plugin and strip out comments
  - **Pros**
    - Doesn't require us to fork the plugin
  - **Cons**
    - Bespoke code; would likely have to write our _own_ plugin
    - Could get a bit messy

Regardless of how we proceed, we could likely implement the solution by stripping out any lines from the injected text which match either of the following regexes:

- `^\s*(//|#)\s*[a-zA-Z]+\(\)\s*{$`
- `^\s*(//|#)\s*}$`

(These could be combined into one but regex is already messy as it is)

**Comment by fundthmcalculus** [comment]
### Thoughts
* outstanding PR is something he approved, but I need to write the test cases before it can be merged. It's been on back burner with all the other high priority issues
* forking permanently on our end only causes additional fragmentation and ongoing maintenance on our end. We would be better served, and better serve the community, by keeping it upstream. The current search only looks for a java-style function definition, eg `myFunction() {`. The preceding comment character(s) are irrelevant.
* Nested code injection blocks seems like a documentation code smell to me. The current situation with those were due to my lack of time to separate such code samples out. We should fix the problem with the docs, not band-aid a solution via major plugin modifications.
* The strip regexs have the potential problem of breaking all sorts of things in Java, a language we support. Also go might have issues. I'd rather not strip things given the option.
* Let me connect with the upstream maintainer and see what he thinks. I'm much more amenable to stripping if it becomes part of the upstream package.

**Comment by geel9** [comment]
> forking permanently on our end only causes additional fragmentation and ongoing maintenance on our end. We would be better served, and better serve the community, by keeping it upstream. The current search only looks for a java-style function definition, eg `myFunction() {`. The preceding comment character(s) are irrelevant.

Agreed that forking permanently on our end is not a great idea.

Though, to note: the current search actually only looks for the token on any line, in any form, and includes the content of the next bracket pair it finds after that token. It doesn't have any notion of comments, function definitions, etc. -- just tokens and bracket pairs.

This is what complicates the issue: what we need to _not include_ is much more specific than the plugin currently concerns itself with. We've decided to use the Java-style syntax when we write target comments, but that's not actually baked into the plugin at all.

> * The strip regexs have the potential problem of breaking all sorts of things in Java, a language we support. Also go might have issues. I'd rather not strip things given the option.

It's definitely fraught with peril... regex is a fickle mistress. Any solution which doesn't rely on it would be ideal IMO.

I'm curious about the specific Java issues you're foreseeing.

> Nested code injection blocks seems like a documentation code smell to me. The current situation with those were due to my lack of time to separate such code samples out. We should fix the problem with the docs, not band-aid a solution via major plugin modifications.

Ultimately, I think this is the cleanest solution for the net result, but it's also going to be a large task to rework all the injection sites to ensure nothing is nested.

**Comment by tmarkovski** [comment]
Do we have to use nested injection comments? Seems like so much work to get around it, and I'm not sure if the benefit is worth it.

**Comment by fundthmcalculus** [comment]
> Do we have to use nested injection comments? Seems like so much work to get around it, and I'm not sure if the benefit is worth it.

No we don't, and we really shouldn't. We have them because I was trying to meet a deadline for @michaeldboyd . Rather than trying to update the plugin, we should simply fix the nested injection comments.

**Comment by geel9** [comment]
Seems like a good route to me. 

I'll create a new issue soon tracking where these occur so we can tackle them.
