### ISSUE TITLE
Optional/Required Protobuf Message Field Documentation

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#618]
Presently, the documentation for our protobuf messages (that is, the comments in the `.proto` files themselves) indicate that a field is optional in an arbitrary way. Sometimes, the description is suffixed by `(optional)` or `(required)`; sometimes a full sentence is used to indicate whether a field is optional; and other times this information is omitted entirely.

For the sake of a uniform style, we should have a single method of indicating whether or not a field is optional.

Some ideas:

- Prefix or suffix field comment with `[optional]`, `(optional)`, etc.
  - On the documentation side, we could additionally parse this out and render the information in a nicer way.
    - For example, we could suffix a type with `?`, ie, `string?`, or render a small badge.
- Use the `optional` label [re-introduced in protobuf 3.15](https://github.com/protocolbuffers/protobuf/blob/main/docs/field_presence.md)
  - This would change the actual semantics of the protobuf fields in a possibly undesirable way.
  - Not supported for repeated fields, so another way to indicate that a repeated field is optional on our end would still be necessary.
- Create an `optional` field attribute, which would only be used for the documentation generation
  - IE, `int32 foo = 1 [optional=true];`

**Comment by fundthmcalculus** [comment]
### Thoughts
1. I dislike comments containing structured data in general, attributes are a thing for a reason. I don't think this would be ideal.
2. Probably best, updating to protobuf 3.15 isn't such a big deal, in fact we're already there for most languages, if not all.
3. `optional` field attribute is probably our best bet. It gives us the best of both worlds. It's structured, while also not changing the protobuf semantics in a meaningful way.

**Comment by geel9** [comment]
Agreed on comments containing structured data; this should only be used as a last resort.

Also agreed on not using the `optional` label; this would be a very large semantic change (and likely introduce bugs) for what is ultimately a documentation feature.

Seems that creating a custom field option is the way to go... only caveat is that it'll have to be namespaced (ie, `trinsic.optional`) as top-level options can only be used in the same file they're declared.


@tmarkovski and/or @sethjback should definitely provide feedback as this will touch their areas of concern.

Specifically, the proposal is to add a `[trinsic.optional = true]` option to fields which are optional, to enable richer documentation tooling and remove the need to specify if a field is required/optional in the comments of said field.

**Comment by tmarkovski** [comment]
Field options is a good approach, as processors are aware of it. We already use message and field options in our [DB schema](https://github.com/trinsic-id/server/blob/aaccef379faf7771b73643a450ac784433ba2e5a/proto/internal/db/config/v1/config.proto#L17). These can be used without namespacing, too.

**Comment by fundthmcalculus** [comment]
> Field options is a good approach, as processors are aware of it. We already use message and field options in our [DB schema](https://github.com/trinsic-id/server/blob/aaccef379faf7771b73643a450ac784433ba2e5a/proto/internal/db/config/v1/config.proto#L17). These can be used without namespacing, too.

Sweet. We will go this route. I can update plugins to output this information wherever we need it. @geel9 I'd say we have a resolution for this ticket.

**Comment by tmarkovski** [comment]
You can also link the PR once it's created with this Issue. That way there's a link between the discussion and the code changes.
