### ISSUE TITLE
Documentation code tabs cause page to jump around

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#619]
Scroll position is not maintained due to linked code tabs all updating.

The [pymdownx.tabbed example](https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/#linked-tabs) for integrating linked tabs has code for maintaining scroll position, but we don't use this -- we instead use the `content.tabs.link` feature in `mkdocs-material` insider, which doesn't seem to maintain scroll position when linked tabs are updated.

Will likely need to submit a PR to `mkdocs-material` to resolve this issue.

<img src="https://user-images.githubusercontent.com/1294419/166709893-4f811c4d-5c32-466e-972e-19c29337b5b4.gif" width="500"/>

**Comment by geel9** [comment]
This seems to only happen sporadically; I need to figure out exactly what conditions cause this to occur.

**Comment by tmarkovski** [comment]
While it's super annoying, it seems once the user has selected a language, it'll be always set by default.

**Comment by geel9** [comment]
Closed by #834
