### ISSUE TITLE
Nested Code Injection Targets

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#620]
- `dotnet/index.md`
    - **Configuration**
      - `testSignInAndGetInfo()` targeted, includes nested `accountServiceConstructor()`, `accountServiceSignIn()`, `accountServiceGetInfo()`
        - `accountServiceConstructor()` targeted in `reference/index.md`, "Using an SDK Service" section, C# tab
        - `accountServiceSignIn()` targeted in `account-service.md`, "Sign In" section, C# tab
        - `accountServiceGetInfo()` targeted in `account-service.md`, "Get Account Info" section, C# tab

**Comment by fundthmcalculus** [comment]
Good work! I'll take a pass through this.

**Comment by fundthmcalculus** [comment]
This is already done. Thanks @geel9
