### ISSUE TITLE
Release SDK v1.6.0

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#633]
# Description

This issue is tracking steps to complete a release ensuring all artifacts are correctly produced. This covers both automated tasks and manual tasks.

We need to flesh out a bunch of things for the 1.6 release. Let's coordinate here to ensure none of the breaking changes are dropped.

# Release

Manual steps are instructions that need to be taken in order to have a full release on all associated repos. Validation steps consist of checklist of items to verify, to ensure all reqiuirements and releases have gone without problems and that the correct assets are created needed for the manual steps.

# Validation Steps

- [x] Builds complete successfully
- [x] Release actions complete successfully
- [x] **Assets** &mdash; ensure the following assets have been created by the release actions and are uploaded as assets in the release
    - [x] Debian Package, named `trinsic_X.X.0_amd64.deb`
    - [x] Trinsic CLI tarball (for Homebrew), named `trinsic-cli-X.X.0.tar.gz`
    - [x] Trinsic CLI vendored tarball (for Homebrew), named `trinsic-cli-vendor-X.X.0.tar.gz`
    - [x] Trinsic CLI Microsoft Installer (msi), name `trinsic-cli-X.X.0.msi`
- [x] **Package Releases** &mdash; validate if packages have been correctly released
  - [x] golang tag (`go/vX.X.0`)
  - [x] nuget.org
  - [x] npmjs.com
  - [x] pypi.org
  - [x] rubygems.org

## Manual Steps

- [x] **Github Release** &mdash; create a new release following the semantic versioning guidelines. The next available version should increase either the Major or Minor version, following the semver recommendations. Patch should be set to `0`. This allows individual languages to publish hotfixes under the same version with new patch. An example version format is `v1.2.0`.
  - [x] Ensure code contributions and commits are included in the release description, either by utilizing the GitHub automatic options or entering them manually.
- [x] **Swift Release** &mdash; create new release in associated repository for Swift package at [trinsic-id/sdk-swift](https://github.com/trinsic-id/sdk-swift). The release version in this repo follows a pattern that doesn't include leading `v`. Example release format is `1.2.0`.
- [x] External Tools
  - [x] **Homebrew** &mdash; to create a new tap, follow the instructions at [trinsic-id/homebrew-tap](https://github.com/trinsic-id/homebrew-tap) by making a new PR with the required information. This step depends on a release asset package.
  - [x] **Windows Package Manager** (winget) &mdash; Update PR to the yaml here: https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/trinsic/cli/
  - [x] **NixOS** &mdash; TODO: Add details
- [x] **Samples** &mdash; if required, code samples at https://github.com/trinsic-id/sdk-examples should be updated to match the version
- [x] Release announced to Trinsic Team

**Comment by geel9** [comment]
- [x] **SDKs**
  - [x] Verify that addition of `options/options.proto` doesn't break any SDKs
    - _(It broke something on the backend, and a project file had to be updated)_
  - [x] **Trust Registry Changes**
    - [x] `AddFrameworkRequest` and `RemoveFrameworkRequest` no longer have a `governance_framework` field
    - [x]  Calls relating to Issuers and Verifiers (ie `RegisterIssuer`) no longer exist; changed to `Member` calls (ie `RegisterMember`)
- [x] **Documentation**
  - [x] Update `trust-registry-service.md` to reflect changes
  - [x] Fully document Trust Registry proto fields and messages

**Comment by fundthmcalculus** [comment]
Need to include messaging about refactor of the go protos into folders. @sethjback @fundthmcalculus 
Need to mention breaking changes for tsproto and typescript @michaeldboyd @fundthmcalculus

**Comment by fundthmcalculus** [comment]
Need to include messaging about `AccountInfoResponse` vs `InfoResponse`, since we're going to have `EcosystemInfoResponse` as well. API hasn't changed, just a compile change.

**Comment by fundthmcalculus** [comment]
Mention new `Login` `LoginConfirm` flow, @geel9 @tmarkovski

**Comment by fundthmcalculus** [comment]
Mention new `Login` `LoginConfirm` flow, @geel9 @tmarkovski

**Comment by michaeldboyd** [comment]
- [x] Make 1.5 -> 1.6 release migration markdown doc
  - [x] typescript has changes - show some samples between 1.5 & 1.6

**Comment by fundthmcalculus** [comment]
Homebrew: https://github.com/trinsic-id/homebrew-tap/pull/19
Winget: https://github.com/microsoft/winget-pkgs/pull/64730

**Comment by fundthmcalculus** [comment]
SDK Examples here: https://github.com/trinsic-id/sdk/pull/825

**Comment by geel9** [comment]
Can this be closed?

**Comment by fundthmcalculus** [comment]
Yes, closing.
