### ISSUE TITLE
Document intricacies of using SQL to query data

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#642]
- Provide a schema for tables (`id`, `type`, `data`)
  - For non-Wallet endpoints, provide more definition
- Direct users to Cosmos DB documentation
- Maybe provide documentation around common pitfalls (`OFFSET` before `LIMIT`, etc)
- Look into existing documentation in our docs around this first

**Comment by michaeldboyd** [comment]
- add an in-page table for the sql schema that people can query against
- mabe a page where we can describe more about the SQL dialect.
