### ISSUE TITLE
Rework `Tools & SDKs` section

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#651]
- Landing page for entire section
  - Based on developer motivation (verifier, issuer, etc.) direct them to the tools they will need
- Possibly workshop different navigation tree for this section
  - Where would we put an OIDC library wrapper we wrote?

**Comment by janpieterz** [comment]
Closed, it's part of ongoing docs improvement which is part of Product Backlog
