### ISSUE TITLE
Rework `Resources` documentation section

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#652]
- "Resources" is confusing -- should maybe be renamed. What's the difference between "Resources" and "Tools & SDKs" (without looking into their contents)?
- Roadmap is not really a roadmap
- Make it clear that some of these links are external / app links, not doc pages
- Workshop the names of the sidebar items, maybe merge some
  - `Join the Community` can be merged/embedded into `Ask a Question`, for instance

**Comment by janpieterz** [comment]
Closed as part of ongoing docs improvement is part of Product Backlog
