### ISSUE TITLE
Vaccine Walkthrough Fixes

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#659]
## Issues
- [x] Ecosystem Creation should be the first step; everything else should occur within said ecosystem
  - [x] After Ecosystem Creation, we should add a step to set the created Ecosystem as the active one for all further steps
- [x] Fix Templates to have the same, valid, form between all languages
  - Each language seems to have a slightly (or wildly) different Template; none of them seem to actually be a _Vaccine_ credential Template.
  - This is related to the discussion point below about test code injection; these templates are being injected from test suites for each SDK language, but these test suites aren't specific to this walkthrough. This causes them to have mismatched template fields.
  - [x] C#
  - [x] Typescript
  - [x] Python
  - [x] Java
  - [x] Go
  - [x] CLI
- [x] Credential should be issued using `IssueFromTemplate`, instead of constructing a JSON-LD Credential and issuing against that.
  - This also fixes the fact that `vaccination-certificate-unsigned.jsonld` has hardcoded `issuer`, schema, etc. which won't be valid when actually used by follower of walkthrough
  - [x] C#
  - [x] Typescript
  - [x] Python
  - [x] Java
  - [x] Go
  - [x] CLI
- [x] Proof should be created for entire credential; don't include JSON-LD Frames in this tutorial
  - [x] Add infobox explaining advanced usage to restrict fields requested
  - [x] C#
  - [x] Typescript
  - [x] Python
  - [x] Java
  - [x] Go
  - [x] CLI
- [x] Fix `batchNumber` template type to be NUMBER
  - [x] C#
  - [x] Typescript
  - [x] Python
  - [x] Java
  - [x] Go
  - [x] CLI
- [x] Explanatory prose should be added to `Create an Ecosystem`
- [x] Explanatory prose should be added to `Define a Template`
- [x] Text about Replit should be removed until Replits exist
- [x] Template name should be appropriate
  -Should just be `VaccineCertificate`
- [x] CLI Commands are incorrect
  - [x] `trinsic account login` commands use nonexistent `alias`, `description` options
  - [x] `trinsic --profile {profile} {COMMAND}` is used frequently, but this is not valid.
- [x] CLI doesn't show how to switch between profiles correctly
- [x] Go example code for exporting account profile incorrectly treats it as a protobuf object, not a string.
- [x] Do a prose pass on `Send Credential to Allison` section.
- [x] Do a prose pass on `Create Accounts` section
- [x] Do a pass on all post-section infoboxes

## Discussion Points

- The fact that we're simply injecting code from our test suites into this walkthrough is helpful for a number of reasons (it can help ensure that our walkthroughs never contain outdated code), but it also introduces some issues.
  - I think, if we are going to continue to inject code from tests into walkthroughs, we should have a completely isolated test suite _for each walkthrough_; e.g., `Tests_Vaccine_Walkthrough.cs` for dotnet
    - This ensures that the tests are properly formed for the walkthrough (Templates have the right fields, etc.)
    - This also allows us to cleanly add new walkthroughs without having to worry about sharing space in the same test suite with other walkthroughs.

**Comment by fundthmcalculus** [comment]
Vaccine credential template should be in `devops/testdata/*.jsonld` for almost everything save wasm/browser. That is due to limitations of the webpack, but I should spend some time and see if I can webpack that in from the above mentioned directory.
https://github.com/trinsic-id/sdk/blob/main/devops/testdata/vaccination-certificate-frame.jsonld
