### ISSUE TITLE
convert `proto/options/field-options.proto` with `proto/options/options.proto`

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#662]
This is to match the server side naming more closely. Is there anything else that I need to do for this, @sethjback ?

Languages:
- [ ] .NET
- [ ] Go
- [ ] Java
- [ ] Node
- [ ] Python
- [ ] Ruby
- [ ] Swift
- [ ] Web

**Comment by tmarkovski** [comment]
It's prob easier to just make a PR against the server than to track this

**Comment by fundthmcalculus** [comment]
I mean, if that's an option, sweet. It depends on which name is better. This change SDK side is trivial too. that whole automatic proto generation thing. 👍 ⚡
