### ISSUE TITLE
Make all Class Names and Function Calls Consistent

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#669]
We current have some inconsistencies in the naming of the services and functions. We should make them all the same across all languages. My vote is as follows:
* `CredentialService` **singular** - currently `CredentialsService` (I'm fine with `VerifiableCredentialService` as well) - https://github.com/trinsic-id/sdk/pull/681
- [x] .NET
- [x] Go
- [x] Java
- [x] Dart
- [x] Python
- [x] Ruby
- [x] Swift  https://github.com/trinsic-id/sdk-swift/issues/15
- [x] Web

* `TrustRegistryService.AddFramework` - currently `registerGovernanceFramework()` - https://github.com/trinsic-id/sdk/pull/682
* `TrustRegistryService.RemoveFramework` - currently `removeGovernanceFramework()` - https://github.com/trinsic-id/sdk/pull/682

- [x] .NET
- [x] Go
- [x] Java
- [x] Dart
- [x] Python
- [x] Ruby
- [x] Swift  https://github.com/trinsic-id/sdk-swift/issues/15
- [x] Web
- [x] Ensure Ruby returns `[XXX]Response` object on every call
- [x] ~Go needs to return the response objects and errors on all calls except `AccountService.SignIn`~ (completed already)

**Comment by fundthmcalculus** [comment]
All, I'm tagging you in this issue since I want a consensus. My votes are already above. I'm open to being persuaded to other naming schemes. I just want every language to be consistent. Obviously, I'm ignoring `camelCase` vs `snake_case` vs `PascalCase` and related. Just the function and class/module names.

**Comment by janpieterz** [comment]
Would it make sense to do this as a final touch for the V2 release? Agree on consistency idea, but as it's just semantical it feels neater to not burden companies before a V2 major release of the packages, which can then contain a nice "migration guide" mentioning this.

**Comment by geel9** [comment]
1. +1
2. (& 3) Sounds good to me, but I think we should take the opportunity to talk about `Trust Registries` vs. `Governance Frameworks`

There seems to be some equivocation going on between the two terms... for example:

![image](https://user-images.githubusercontent.com/1294419/170066814-988ce971-cd6a-4ecd-840f-eef0302a8383.png)


Does this call add a trust registry? A governance framework? What's ultimately the difference between these two?

Why does the `TrustRegistryService` only expose methods to deal with `[Governance] Frameworks`?

**Comment by fundthmcalculus** [comment]
> Would it make sense to do this as a final touch for the V2 release? Agree on consistency idea, but as it's just semantical it feels neater to not burden companies before a V2 major release of the packages, which can then contain a nice "migration guide" mentioning this.

I like your concern for the customers 👍 , but "1.6" (really `v0.6`) already has breaking changes coming out from @tmarkovski , so I'd rather get a bunch of the breaking changes in together. Anyone using the node/web (now unified typescript SDK) will be hit by the 1.6 because of the change in how we support typescript, regardless of the other changes.

Post GA, I want to be much more careful about breaking syntax changes, and especially API changes. Part of why I'm trying to push the discussion of proper semantic versioning.

**Comment by fundthmcalculus** [comment]
@geel9 
1. I figured this wasn't going to be controversial. 😁 
2&3: definitely a discussion that needs to be completed before GA, if practical, before 1.6.

**Comment by fundthmcalculus** [comment]
Swift has it's own issue, closing this one.
