### ISSUE TITLE
Migrate Azure Repos to Github

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#68]
- [ ] Move all our repositories over to github
- [ ] Import all our bugs as issues
This will need some level of automation, augmented by manual oversight. Ideally, the git repositories can be transferred using a second remote push `--all`. The issues will probably need some kind of migration using the Github API:
https://docs.github.com/en/rest/reference/issues

**Comment by fundthmcalculus** [comment]
@michaeldboyd got a list of repos, or a link to where they are in azure dev? I can easily pull them using some bash scripts. If Azure issues have an xml export, I can automatically move them into github. :)

**Comment by tmarkovski** [comment]
I don't think we have any issues on DevOps that we are actively tracking at this time. @michaeldboyd can you confirm?

**Comment by fundthmcalculus** [comment]
@tmarkovski @michaeldboyd can this issue be closed as "won't do"?

**Comment by tmarkovski** [comment]
I think so, but lets get @michaeldboyd sign off
