### ISSUE TITLE
CLI: Add `--out` param to `account login`

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#691]
As a user, I want to be able to log in to an account via the Trinsic CLI, and have the authentication token saved to an arbitrary file of my choosing.

This would look like:

`trinsic account login --name "Allison" --out "allison.txt"`

Because of the way the response is formatted to the console, it's non-trivial to do this in bash currently -- extracting _just_ the auth token from the formatted output is annoying.

This would also have benefits for our walkthroughs. Presently, we [awkwardly ask users to do this by hand](https://user-images.githubusercontent.com/1294419/171429443-0057864d-0f09-40b7-946e-f8217b26c6e3.png), which is annoying and disrupts the flow of the walkthrough.

**Comment by tmarkovski** [comment]
I agree, the utility of the CLI can be improved by allowing machine readable data to be processed with scripts and automation. One way to achieve this is to use simple output instead formatted one, which can then be piped into a file or assigned to a shell variable.

```bash
trinsic account login > output.txt

# or

export ALICE=$(trinsic account login)
```

This can then be applied to commands like issuance

```
trinsic vc issue > cred.json
```

**Comment by tmarkovski** [comment]
Pulumi does this by providing a flag how to format the output

<img width="778" alt="image" src="https://user-images.githubusercontent.com/1280118/171485218-da6205a5-0d11-45a4-9173-7bc9c21a200e.png">

Seems like a way to go.

**Comment by geel9** [comment]
So, we need to:

- Identify the flag name (I don't like `color` -- how about `format`?)
- Determine the possible values
  - For now, `default` (current behavior) and `raw` (single value as text) make sense to me
- Identify the commands which should support this flag
- Determine what to actually export for each command
  - For `login`, the auth token is the obvious choice.
  - What about `template create`? Should it be the entire template JSON blob, the template ID?
- Implement functionality for each identified command

**Comment by fundthmcalculus** [comment]
> * Identify the flag name (I don't like `color` -- how about `format`?)
> * Determine the possible values 
>   * For now, `default` (current behavior) and `raw` (single value as text) make sense to me

How about `style`? `format` could indicate that you can provide a format string specifier, which is sometimes used for logging. We are _styling_ the output, not changing the format of it.

> * Identify the commands which should support this flag

All of them.

> * Determine what to actually export for each command
>   * For `login`, the auth token is the obvious choice.
>   * What about `template create`? Should it be the entire template JSON blob, the template ID?
> * Implement functionality for each identified command

I'd argue that everything in the response should be shown as JSON by default. We can't know what the user is going to want, so we shouldn't *ass*ume what they want. For `login` and related, where the programming language calls are wrapping the `LoginResponse` as a string (or something else), let's do the same for CLI for parity.

**Comment by tmarkovski** [comment]
Things are shown colorized for friendliness, but the idea is to be able to switch with a flag. The output result is actually a dictionary, so we can easily serialize it as JSON instead. Getting machine readable output is the end goal.
