### ISSUE TITLE
New Login -- type mismatch for immediate vs. confirmed login

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#743]
## Problem

With the new login method, the expected flow is:

- Login, receive `LoginResponse`
- LoginConfirm, passing `challenge` from `LoginResponse`, receive `LoginConfirmResponse` (or a `string`)

However, if the initial `Login` results in a successful login with no challenge necessary, the `LoginConfirm` step is unnecessary, **and the object we return from the `Login` function should likely be the auth token itself**

That is, there are two flows:

1. `Login` -> no challenge -> auth token string
2. `Login` -> challenge -> `LoginResponse` -> `LoginConfirm` -> auth token string

An example of the problem can be seen in the method signatures (.NET as example):

```csharp
public LoginResponse Login(LoginRequest request);
public string LoginConfirm(LoginConfirmRequest request);
```

As a developer, if I call `Login`, and the returned `LoginResponse` indicates that no confirmation is necessary, **how do I get an auth token string?**

#### No Unchallenged Logins

Simply remove the possibility that a login can go unchallenged.

Logins only go unchallenged, presently, when an anonymous account is created as a result of a login.

Therefore, we could either remove the ability to create anonymous accounts in the first place, **or** remove implicit account creation (ie, accounts can only be created via a dedicated `CreateAccount` method).

#### `LoginAnonymous` SDK method

Only allow anonymous account creation via a special `LoginAnonymous` method (SDK wrapper around `Login`, no new proto method necessary), which just returns an auth token string immediately.

#### Always use `LoginConfirm` regardless

Just tell developers to always use `LoginConfirm`.

The client library could simply take a shortcut and return the encoded auth token without even making an API request.

#### Force devs to convert `LoginResponse.Profile` to auth token themselves

Cumbersome for them, but easiest for us.

Could easily expose helper methods -- `ProfileToAuthToken`/`AuthTokenToProfile` -- to assist with this.

**Comment by tmarkovski** [comment]
What is in the endpoint proto definition and what is exposed in the SDK can be two different things.
I'm not opposed to the idea of having Login/LoginConfirm and LoginAnonymous separately in the SDK.
Both LoginConfirm and LoginAnonymous should return the AuthToken as string, not the AccountProfile object as whole, which is one abstraction we're doing. Devs shouldn't worry about what goes in AuthToken.

A reminder, most Login use cases will be done by Wallet providers, which will not be the majority of our users. The majority will be coming as Issuers / Verifiers, in which case they'll have pre-generated AuthToken as part of their onboarding process.
Login endpoints will be used primarily by us and a select few providers who decide they want to build their own Holder experience.
I'm mentioning this so we're careful not to over-optimize these flows for broad use.

**Comment by fundthmcalculus** [comment]
For the most part, anonymous login is for testing, which can be slightly more cumbersome if needed. I'd rather keep the SDK abstractions to a minimum for the present, while we are figuring out what we are sharing with users. I think `LoginAnoymous` should probably be internal endpoint, since what customer is going to use that in a real world setting?

**Comment by geel9** [comment]
The motivation for this issue is that we are explicitly telling customers to create anonymous accounts in our walkthrough, and in every code sample.

Which makes sense -- we want to reduce the friction of following our walkthrough. Simply creating accounts is much smoother than "Create account 1... go to your email... copy code over. Create account 2... go to your email [...]"

**Comment by fundthmcalculus** [comment]
> 

Agreed. Then let's make the `LoginAnonymous` endpoint.

**Comment by fundthmcalculus** [comment]
Relevant execution ticket: https://github.com/trinsic-id/sdk/issues/750
