### ISSUE TITLE
`Learn -> Platform` section

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#748]
Currently, the `Learn` docs section has two sections: `Key Concepts` and `Tutorials`

- Change `Key Concepts` to something like `SSI Concepts`, `Identity Concepts`, etc.
- Add `Platform` (or other name) section
  - Contains documentation around various aspects of the platform
  - `Webhooks`, `Login Flow`, `Authentication Tokens`, etc.
  - Start with just `Webhooks`

**Comment by michaeldboyd** [comment]
@geel9 I'll be working on the docs this week, will assign this to myself

**Comment by michaeldboyd** [comment]
- [ ] document authentication scheme
- [ ] document each individual event type 
- [ ] prep instruqt for webhooks and other how-to guides
- [ ] maybe add a verify webhook util function

**Comment by michaeldboyd** [comment]
- [ ] document event types using protobuf objects in our references
