### ISSUE TITLE
Go SDK

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#76]
- [x] Okapi
- [x] Services

**Comment by fundthmcalculus** [comment]
Go C FFI interop on windows is basically unsupported. I'd argue this should be a LINUX/MacOS environment focus, Windows added if requested.

**Comment by tmarkovski** [comment]
Yikes. Considering Go is mostly a server side platform, it would be run under Linux, so that's fine. I'm curious to learn about the Windows FFI challenge for Go. Got any links?

**Comment by fundthmcalculus** [comment]
https://dave.cheney.net/2016/01/18/cgo-is-not-go
https://blog.filippo.io/rustgo/
https://golang.org/pkg/plugin/ (Plugins only supported on Linux and MacOS) : https://stackoverflow.com/questions/24641296/load-package-dynamically
The internet has a bunch of cases of the reverse (Rust calling into Go), very little on successful (Go calling Rust).
Part of it is the compiler `.out` linker formats changing between Rust and Go. Hmmm, I wonder if I can adjust the Rust compiler on windows...
