### ISSUE TITLE
Add testing support for the CLI

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#765]
We need to test the CLI behavior with some shell script commands. This is blocked by the non-formatted output #691 .

**Comment by geel9** [comment]
Seems like this has been (partially?) resolved by #777 and #778

**Comment by fundthmcalculus** [comment]
Partially, not completely. Definitely a good start.

**Comment by tmarkovski** [comment]
> Partially, not completely. Definitely a good start.

What's missing?

**Comment by fundthmcalculus** [comment]
> > Partially, not completely. Definitely a good start.
> 
> What's missing?

Mostly an action to run this, which I can easily do.
