### ISSUE TITLE
Interactive Walkthrough for Webhooks

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#768]
We should create an interactive tutorial which guides a developer through the process of:

- Setting up simple web app (node?) which will receive webhooks from Trinsic
- Creating an Ecosystem (or using a pre-provisioned one)
- Creating account within Ecosystem
- Authorizing webhooks for account
- Adding webhook to ecosystem
- Verification of HMAC of incoming webhooks in web app

**Comment by geel9** [comment]
This should serve as a good exploration of Instruqt.

**Comment by janpieterz** [comment]
Closed as part of ongoing docs improvement is part of Product Backlog
