### ISSUE TITLE
Update all code samples for uniservice design

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#773]
All code samples must be updated to account for the new "single-service" design.

Specifically, services should be accessed through a `trinsic` variable, which is an instance of `TrinsicService`.

No sample should use individual instances of services.

**Languages**
- [x] .NET
- [x] Typescript
- [x] Go
- [x] Java
- [x] Python
- [x] Ruby
- [x] Swift
- [x] Dart

**Comment by fundthmcalculus** [comment]
I'll just take this issue as a whole.

**Comment by fundthmcalculus** [comment]
Ruby/Swift/Dart don't have code samples, so are out of scope.
