### ISSUE TITLE
Allow Server to Perform input validation

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#818]
Remove sanity checks from the SDKs, since that requires inconsistent, repeated code across multiple languages. The server will provide the error checking and return an error if the inputs provided are invalid. This reduces code duplication, as well as increases the ability to automatically generate the SDK layer

Languages:
- [x] .NET
- [x] CLI
- [x] Go
- [x] Java
- [x] Dart
- [x] Python
- [x] Ruby
- [x] Swift
- [x] Typescript

**Comment by geel9** [comment]
A lot of this can be done by #813 automatically, by just not `ignore`ing the methods in question.

**Comment by fundthmcalculus** [comment]
> A lot of this can be done by #813 automatically, by just not `ignore`ing the methods in question.

Yup, that's the plan. Part of the goal will be to reduce the number of methods we `ignore`. Ideally only the signin methods, if any. I'd rather rename the user-created wrapper methods where possible, so that we can auto generate everything. Certainly for `search`, we need to rename to be consistent between `WalletService` and `TemplateService`.

**Comment by fundthmcalculus** [comment]
A good chunk of this is already done, @janpieterz if you aren't opposed, I'd like to scope this into the current sprint.

**Comment by janpieterz** [comment]
@fundthmcalculus I would like to, maybe we first finish the committed work for GA? If there's space at the end, why not.

**Comment by fundthmcalculus** [comment]
Key work for this was already done.
