### ISSUE TITLE
Add / Normalize `SetAuthToken()` method

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#828]
Every language should have a `SetAuthToken()` function in the base service class.

Some languages have this exactly; some have a similar function, but with a different name (ie `SetProfile` in Java); some lack it entirely

Languages:
- [x] CLI
- [x] .NET
- [x] Dart
- [x] Go
  - Exists as `SetToken`
- [x] Java
  - Exists as `setProfile`
- [x] Python
- [x] ~Ruby~
- [x] ~Swift~ https://github.com/trinsic-id/sdk-swift/issues/25
- [x] Typescript

**Comment by fundthmcalculus** [comment]
Ruby is idiomatic, so setup is required.

**Comment by tmarkovski** [comment]
Does this method need to be public? What production use case does this method support?

**Comment by fundthmcalculus** [comment]
> Does this method need to be public? What production use case does this method support?

We use this to set the auth token during samples/unit tests. Thus, it will be public.

**Comment by geel9** [comment]
It's necessary to have decent-looking samples for, EG, the Vaccine Walkthrough.


This method will typically not be used to switch *between* auth tokens by our customers, but I predict it will be used often anyways.

For example, a mobile wallet might save an auth token in a secure enclave, and upon launch of the app, will need to configure the SDK to use the auth token -- sure, you can set this during instantiation of `TrinsicService`, but they very well may want to do it post-instantiation as well.
