### ISSUE TITLE
Deprecate and remove `default_ecosystem` in service options

### ISSUE THREAD

**Issue by tmarkovski** [Dentity-Development/dentity-ecosystems-sdk#836]
This no longer provides any value. When the `authToken` is set in the configuration, changing `default_ecosystem` has no effect. It's only used during login, when the `ecosystem` field is not provided. It seems we can completely remove this from the SdkOptions and rely on defaults in the server, if this is omitted.

**Comment by geel9** [comment]
@fundthmcalculus and I had a discussion about this the other day -- I'm in complete agreement.

**Comment by janpieterz** [comment]
GA candidate? @fundthmcalculus is it feasible this sprint?

**Comment by fundthmcalculus** [comment]
> GA candidate? @fundthmcalculus is it feasible this sprint?

Totally. This is basically a quick proto change, everything from there on is essentially automated.

**Comment by geel9** [comment]
It's a sample / SDK change as well, but not bad to do.

**Comment by janpieterz** [comment]
Awesome, moved to in progress for this sprint then.

**Comment by fundthmcalculus** [comment]
@sethjback @tmarkovski is it fair to assume that if we don't send an ecosystem on login, the server automatically signs into the `default` ecosystem?
