### ISSUE TITLE
Add SDK language and version to User-Agent header

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#845]
This metadata allows us to identify which version of the SDK is being used (useful to determine when we can remove deprecated endpoints, etc), which language is being used (metrics), which version of okapi is being used (oberon information).

Languages:
- [x] CLI https://github.com/trinsic-id/sdk/pull/872
- [x] .NET #855 
- [x] Dart https://github.com/trinsic-id/sdk/pull/860
- [x] Go https://github.com/trinsic-id/sdk/pull/861
- [x] Java https://github.com/trinsic-id/sdk/pull/862
- [x] Python https://github.com/trinsic-id/sdk/pull/865
- [x] Ruby https://github.com/trinsic-id/sdk/pull/866
- [x] Swift https://github.com/trinsic-id/sdk-swift/pull/28
- [x] Typescript https://github.com/trinsic-id/sdk/pull/868

**Comment by geel9** [comment]
What should the header names be? Needs to be written down to ensure consistency across languages.

Suggestions:

- `TrinsicSDKLanguage`
  - `dotnet`
  - `typescript`
  - `python`
  - `java` / `kotlin`
  - `golang`
  - `ruby`
- `TrinsicSDKVersion`
  - Alternatively, language-specific header?
    - IE, `TrinsicSDKVersion-dotnet`
- `TrinsicOkapiVersion`

**Comment by fundthmcalculus** [comment]
> What should the header names be? Needs to be written down to ensure consistency across languages.
> 
> Suggestions:
> 
> * `TrinsicSDKLanguage`
>   
>   * `dotnet`
>   * `typescript`
>   * `python`
>   * `java` / `kotlin`
>   * `golang`
>   * `ruby`

> * `TrinsicSDKVersion`
>   
>   * Alternatively, language-specific header?
>     
>     * IE, `TrinsicSDKVersion-dotnet`

I don't like this, it makes part of the value information selector in the key.
How about: `TrinsicSDKLanguage=""` `TrinsicSDKVersion=""`?

> * `TrinsicOkapiVersion`

This is easy enough.

**Comment by geel9** [comment]
Agreed, I don't like having the key be specific to the language either -- figured I'd throw it out as an option, though.

**Comment by fundthmcalculus** [comment]
> Agreed, I don't like having the key be specific to the language either -- figured I'd throw it out as an option, though.

Let's make a proto specification for this, so that it's more consistent.

```protobuf
// Configuration for Trinsic SDK Services
message SdkMetadata {
    // okapi version
    string okapi_version = 1;
    // Sdk Language client
    string language = 2;
    // Version of the language SDK
    string language_version = 3;
}
```

**Comment by geel9** [comment]
Would we serialize this message to bytes and set a single header in the request? If so, personally I'm a -1 on that.

It'd prevent us from doing simple analytics on the backend -- for example, through Cloudflare -- as simple tools wouldn't understand that serialized header. We'd need to do some transformation first before it became usable.

**Comment by fundthmcalculus** [comment]
> Would we serialize this message to bytes and set a single header in the request? If so, personally I'm a -1 on that.
> 
> It'd prevent us from doing simple analytics on the backend -- for example, through Cloudflare -- as simple tools wouldn't understand that serialized header. We'd need to do some transformation first before it became usable.

Good points there. I just want to ensure every field is consistent across all languages. Maybe KVP serialization similar to the `Authorization` header?

**Comment by geel9** [comment]
Given that it's a one-off per language, I'm fine with just setting explicit headers -- see #855 for my .NET implementation

**Comment by janpieterz** [comment]
Why not use the default http user agent header? It's pretty spot on for this use case I think, and well supported. We definitely need this to be in text as we'll likely feed this to logging before it even hits anything GRPC or Protobuf aware

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent


If they can do this, I bet we can morph in all we need to:
> Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0
Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by janpieterz** [comment]
Some options:
`TrinsicSDK/2.0.1 (OKAPI 2.4; dotnet 6.0)`
or
`TrinsicSDK/2.0.1 OKAPI/2.4 dotnet/6.0`

Not sure if we can retrieve version information of the context always, but that would be optional of course.

**Comment by geel9** [comment]
I think shoving it all into a single header has some pros and some cons.

The pro, in my mind, is that certain parts of our infrastructure (IE Cloudflare) might have tooling specific to the useragent header that might make analytics easier.

The cons, on the other hand, are that shoving everything into a single header limits our analytics capabilities (unless solved by existing tooling, as mentioned above). For example, every single pair of `(language, sdkver, okapiver)` is a distinct useragent string, so a simple aggregate query is useless -- we would need to perform transformation work / string splitting to get the results we want, as opposed to having that splitting work *already done for us* by having them be in separate headers.

At the end of the day, we just want to get this info from point A to point B -- I don't think it matters too much the specific names of the headers, but I do think that the work we'll have to do to make the information *useful* is... somewhat important. The technology to split strings, of course, exists -- so it's not the end of the world if we shove it into a single header. I'm just not personally married to doing it in the "idiomatic HTTP" way, when we're already kind of not doing "real HTTP" by virtue of doing GRPC-over-HTTP (it ain't text).

Ultimately, though, the amount I care about the issue is actually less than the amount of text I've written about it, so I'm fine with a decision being made unilaterally and us just going with it @janpieterz

**Comment by janpieterz** [comment]
Fair point, the ability to query independently and in combination is a good point, often you'll end up with the header just being parsed as a string into whatever log query system.

Maybe we do useragent just as `TrinsicSDK/2.0.1` and then make the other ones more specific headers?

**Comment by fundthmcalculus** [comment]
For every language except typescript, we use HTTP2, not HTTP1.1.
In gRPC, the notion of user agent isn't really a thing, since we have a defined protocol, not variable platform  implementations. That said, maybe we should send OS information as well?
gRPC metadata is designed to be sent as a map of string key value pairs, which lends itself towards splitting the information into separate fields, much like the `authorization` header. Since we parse the metadata at the server level, I would vote for logging the information there as well.

**Comment by janpieterz** [comment]
Is that metadata set on the HTTP transport level headers?  
It feels cleaner to do this kind of debug information (just like request tracing ids etc.) onto HTTP rather than GRPC

**Comment by fundthmcalculus** [comment]
It's in the gRPC protocol. We can't access the HTTP information directly. The recommended way from google to send this type of data is the `metadata` field.

**Comment by janpieterz** [comment]
Mmmh, interesting abstraction.

For [C# all metadata seems to be sent as http headers](https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-7.0#bearer-token-authentication). 
> Entries in the Metadata collection are sent with a gRPC call as HTTP headers:

Does that work the same for others you think? It'll be neat to have the same transport mechanism and ideally before GRPC kicks in, that way certain proxies etc. can already log and act on this without it needing GRPC awareness.

**Comment by fundthmcalculus** [comment]
> Does it work that way in other languages?

[It appears so](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md). I just dislike the typical useragent string, since it seems super busy with everything crammed together.

> Maybe we do useragent just as `TrinsicSDK/2.0.1` and then make the other ones more specific headers?

We don't send a useragent, so this wouldn't be necessary. This is in keeping with everything in separate metadata fields, which seems like the way to go. It will be a lot easier for analytics to `SELECT c.SdkVersion, c.OkapiVersion, c.SdkLanguage WHERE c.OkapiVersion > '1.6.0'` vs trying to string split the data and get what we want.
