### ISSUE TITLE
Python SDK Documentation

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#86]
Python - @michaeldboyd 
 - [x] By Sept 20th - Documentation - update existing documentation with snippets, walkthrough additions and anything specific to Python that users should be directed https://github.com/trinsic-id/sdk/pull/125
  - [x] By Sept 20th - Samples - provide basic usage for working with wallet and managing profiles. Use citizenship or vaccination vocabulary for sample credentials to work with.  https://github.com/trinsic-id/sdk/pull/125
  - [ ] By Sept 20th - Reference server in Python
  - [ ] Repl.it example

**Comment by fundthmcalculus** [comment]
Let's decide shortly whether sample applications live in the same repository as the SDKs (okapi and services), or in a separate repository. @tmarkovski @michaeldboyd thoughts? I want to make sure we do this right the first time. :)
