### ISSUE TITLE
Create SDK version constant to report over the metadata headers.

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#870]
We need to support SDK version information for metadata header reporting. Some languages are done since they support dynamic file reporting. Some require a release-time updated constant.

Languages:
- [x] CLI
- [x] .NET
- [x] Dart
- [x] Go
- [x] Java
- [x] Python
- [x] Ruby
- [x] Swift https://github.com/trinsic-id/sdk-swift/issues/29
- [x] Typescript

**Comment by janpieterz** [comment]
Can you update which languages are done already @fundthmcalculus ?

**Comment by fundthmcalculus** [comment]
@janpieterz done.
