### ISSUE TITLE
OIDC Documentation Improvements

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#875]
The OIDC documentation needs to be improved:

- Improve discoverability of OIDC service in documentation
  - OIDC credential exchange completes our product offering -- it's what enables VCs to have value in ecosystems. Therefore, it should be called out as a first-class offering.
- Build OIDC credential exchange into our walkthrough section
  - Either build a tutorial dedicated to it, or include it in our existing vaccine tutorial
    - The vaccine tutorial is already _quite large_; adding OIDC massively expands the scope
    - OIDC-specific tutorial should assume you already have an ecosystem provisioned, ability to issue credentials, etc., and go from there
- ~Improve the look of `Configuration` section~
  - ~Change bullet points to table?~
- ~Document trust registry configuration parameter~
- ~Improve look of JSON blob~
- ~Direct visitors to recommended OIDC libraries in various languages, including Android/iOS~
- Create additional samples (will be tracked by additional issues)
  - Server-side verification
  - Android
  - iOS
- Create Instruqt tutorials? (Will be tracked by additional issues)
  - Client-side / server-side

**Comment by tmarkovski** [comment]
I'd be happy to contribute to this in whatever capacity it makes sense. We also have some dev work around customization, but that's not until few sprints.

**Comment by janpieterz** [comment]
Closed as part of ongoing docs improvement is part of Product Backlog
