### ISSUE TITLE
Split SDK typescript package for node/web

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#895]
Due to bundlers other than webpack not honoring the `"browser"` tag in `package.json`, we need to split the node and web typescript packages for our SDK similar to how we split the okapi package. Ideally, we can keep a common codebase, and just rename the `package.json` on publish (which is what we do for okapi). There would be some idiosyncracies with the different package dependencies at the SDK level, so we might need to make two different `package.json` files (if that's possible?)

**Comment by tmarkovski** [comment]
Another argument for doing this is running the node package with grpc on http2, instead grpc-web on http1.1.
I think we can do an `sdk-common` package, which would publish any needed configuration or interface for `sdk-node` and `sdk-web`.

**Comment by fundthmcalculus** [comment]
> Another argument for doing this is running the node package with grpc on http2, instead grpc-web on http1.1. I think we can do an `sdk-common` package, which would publish any needed configuration or interface for `sdk-node` and `sdk-web`.

Maybe? I'd rather keep the count of packages down given the option, but if necessary, we could do this. This would put all the proto definitions in one place, but that's about it.

**Comment by janpieterz** [comment]
Hypothetically there's potential for rollup to use the [node-resolve plugin](https://github.com/rollup/plugins/tree/master/packages/node-resolve) to resolve this correctly rather than use split packages. 

Does not address any http2 issues and other stuff though, so probably still good splitting.

Another option would be to root in a different folder, so:
- `/src`
- `/package-1` => references code from `/src`
- `/package-2` => references code from `/src`

**Comment by sethjback** [comment]
@janpieterz I like there is a plugin to solve the rollup issue, it would be awesome if we could get it to work out of the box though. Having the lowest amount of friction possible for 30% of our sdk users* seems like an important investment.

*I've heard that number - not sure if it's accurate

**Comment by fundthmcalculus** [comment]
The number you quoted is correct per @rileyphughes ?

**Comment by tmarkovski** [comment]
I don't see a big downside for split packages. Browser development use browser specific packages all the time. It feels very fragile to have to maintain compatibility with plugins for every bundler out there. Node and Browser are completely different platforms and runtimes anyway.

**Comment by fundthmcalculus** [comment]
> I don't see a big downside for split packages. Browser development use browser specific packages all the time. It feels very fragile to have to maintain compatibility with plugins for every bundler out there. Node and Browser are completely different platforms and runtimes anyway.

I would add, that plugin fixes it for "rollup" - maybe. It doesn't solve snowpack (Svelte), or others. I'd rather not rely on extraneous plugins to make things happen, when out of the box, we can support everything we need.

**Comment by janpieterz** [comment]
There are some downsides:

1. As a consumer I would not expect this (I've been doing node and browser work for a long time in huge codebases and never experienced separate packages). Not unheard of probably, but not super normal/expected. 
2. If I now want to write an internal package that does the Trinsic interaction, I will need to split up my internal package as well. 

Not saying these should sway the decision for now. We probably should go with this route to just move forward, if we notice the friction is too much we can dive deeper and revisit.

@fundthmcalculus Would you be able to write a summary of all the issues we ran into once you're done for future reference?

**Comment by fundthmcalculus** [comment]
We also have conflicting dependencies when it comes to GRPC and WASM. If we had a pure typescript solution, we could easily make it a singular package, but for now, we can't. It will also be easier once wasm-pack has a common output for node/browser.

(If people would quit trying to shovel typescript into the backend, the problem would likewise resolve itself).

**Comment by tmarkovski** [comment]
The upside of using separate packages is you can always build an umbrella package to do the decision making if you want to combine them, like using "browser" detection or the rollup plugin.

**Comment by tmarkovski** [comment]
https://github.com/connor4312/blake3 uses wasm to publish node and browser versions combined. Maybe we can take some examples from? Seems they use similar approach.

**Comment by fundthmcalculus** [comment]
> https://github.com/connor4312/blake3 uses wasm to publish node and browser versions combined. Maybe we can take some examples from? Seems they use similar approach.

They use the browser tag, which is the underlying problem. They have a nicer, flatter source code layout; they still have the `"browser"` problem that not every bundler respects it.

https://github.com/connor4312/blake3#browser "which works with webpack"

**Comment by sethjback** [comment]
> https://github.com/connor4312/blake3#browser "which works with webpack"

Interesting workaround they mentioned in `blake3/browser-async` - would something like that work in our case?

**Comment by fundthmcalculus** [comment]
> > https://github.com/connor4312/blake3#browser "which works with webpack"
> 
> Interesting workaround they mentioned in `blake3/browser-async` - would something like that work in our case?

This still has the same problem of the `browser` tag and it's an es module, which has issues with commonjs, something we have to support. 😦

**Comment by tmarkovski** [comment]
> > Interesting workaround they mentioned in `blake3/browser-async` - would something like that work in our case?
> 
> This still has the same problem of the `browser` tag and it's an es module, which has issues with commonjs, something we have to support. 😦

What they propose with `browser-async` ignores the "browser" tag feature entirely, since it redirects to completely separate import. This is essentially importing another package.

**Comment by fundthmcalculus** [comment]
> > > Interesting workaround they mentioned in `blake3/browser-async` - would something like that work in our case?
> > 
> > 
> > This still has the same problem of the `browser` tag and it's an es module, which has issues with commonjs, something we have to support. 😦
> 
> What they propose with `browser-async` ignores the "browser" tag feature entirely, since it redirects to completely separate import. This is essentially importing another package.

Would it make sense then to tell people to import `@trinsic/sdk-node` and `@trinsic/sdk-web` from the same NPM package? Thereby, keeping the package count unitary, but the structure completely isolated?

**Comment by tmarkovski** [comment]
In my opinion, that's an acceptable compromise. It would be `@trinsic/sdk/browser` or something similar, since we use scoped NPM, but yes. I think that'll work, if auto-detection doesn't work with their bundler.

**Comment by janpieterz** [comment]
I love that idea, it removes that bit of friction we spoke about. 

Does it also allow us to have specific interfaces, proto generated type definitions etc generic? Meaning, as a consumer I could have code using Trinsic's package in both places roughly like:


Generic code:
```
import {CredentialResponse} from `@trinsic/sdk`
const something: CredentialResponse;
```

Browser code:
```
import CredentialService from `@trinsic/sdk/browser`
```

Node code:
```
import CredentialService from `@trinsic/sdk/node`
```

**Comment by fundthmcalculus** [comment]
@janpieterz let me experiment. I have the SPLIT  packages here: https://github.com/trinsic-id/sdk/pull/899/

* I have made e a new PR prototyping the direct browser import we just discussed: https://github.com/trinsic-id/sdk/pull/902

**Comment by tmarkovski** [comment]
I believe the Services and Models would be shared types. The difference between browser and node would be how they're instantiated, by passing a Provider which would parametrize them with the correct version of gRPC client, wasm loading strategy, etc.

Even if you load `CredentialSevice` from `sdk` or `sdk/browser` it would point to `sdk/services/CredentialService`, it would just have different parameters depending on where you got it from.

**Comment by fundthmcalculus** [comment]
Done with #902
