### ISSUE TITLE
SDK Round 2

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#90]
- [x] https://github.com/trinsic-id/server/issues/184
- [x] https://github.com/trinsic-id/server/issues/180
- [x] https://github.com/trinsic-id/server/issues/182
- [x] https://github.com/trinsic-id/sdk/issues/95
- [x] https://github.com/trinsic-id/sdk/issues/96

**Comment by tmarkovski** [comment]
Descoping https://github.com/trinsic-id/server/issues/181 from current milestone so we can close this
