### ISSUE TITLE
Evaluate `connect-grpc` for future use

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#915]
https://buf.build/blog/connect-web-protobuf-grpc-in-the-browser

* This is a post-1.0 release state, probably December 2022 @janpieterz

**Comment by janpieterz** [comment]
I think we're happy with what we've got, I'd prefer not re-writing our gRPC basis for now. Let's archive, we can always surface it again if someone played around with it.

**Comment by fundthmcalculus** [comment]
This was a note to play around and evaluate it, not implement it.

**Comment by janpieterz** [comment]
Yep, that was clear.
