### ISSUE TITLE
Add analytics to docs

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#924]
We don't currently have any analytics (Google Analytics, Mixpanel, etc.) on our docs site; to ensure that we properly understand our customers' experience with and usage of our docs, we should add some form of analytics suite.

Ideally, we would take care to use a **privacy-preserving** toolset; most optimally, one that we're paying for directly (such that they don't need to use our visitors' data in unethical ways to turn a profit). Practically, this means no Google Analytics unless we absolutely have to.

**Comment by janpieterz** [comment]
Closed as part of ongoing analytics improvement is part of Product Backlog
