### ISSUE TITLE
CLI doesn't include --name in account login command

### ISSUE THREAD

**Issue by michaeldboyd** [Dentity-Development/dentity-ecosystems-sdk#925]
![Image](https://user-images.githubusercontent.com/22651660/184032325-4f776f9c-0a62-4507-b346-08912353b21d.png)

Reference is reflected correctly: https://docs-v2.trinsic.id/reference/services/account-service/#login

But the walkthrough has the incorrect command: https://docs-v2.trinsic.id/walkthroughs/vaccination/#create-accounts

Seems like having a wallet alias / name is valuable, as shown in the walkthrough - but given it's been removed, can we please ensure the walkthrough can be completed with the CLI?

**Comment by tmarkovski** [comment]
I know this is a big ask, I would prefer to change the topic from vaccination to something more usable, like a drivers license. We have full ISO schema in cli/tests.
This might not be the best opportunity for that, but if someone feels adventurous, I'd be happy to guide them.

**Comment by geel9** [comment]
I'm a +1 on switching to a different walkthrough topic -- I very frequently use drivers' licenses as an example of the value-add of SSI, so it makes perfect sense to lead with it
