### ISSUE TITLE
Emojis in branch names break docs preview action

### ISSUE THREAD

**Issue by geel9** [Dentity-Development/dentity-ecosystems-sdk#928]
See #927 for example

Additionally, the URL should include the commit hash, as the branch name is not a sufficiently-unique key.

**Comment by tmarkovski** [comment]
😡😤🤬🥊

**Comment by janpieterz** [comment]
Lol. Assigns ™️ 😂

**Comment by janpieterz** [comment]
Just joking around btw (re assignment)
