### ISSUE TITLE
Craco Wasm Loader Issue

### ISSUE THREAD

**Issue by kashyapshiv** [Dentity-Development/dentity-ecosystems-sdk#931]
### Reproduction steps

Hi, I am trying to integrate my React Application using craco as per the docs,
[](https://docs-v2.trinsic.id/web/#configure-webpack.)

But I am keep getting this webpack error on starting my project. 
![trinsic](https://user-images.githubusercontent.com/105337972/184634204-2fe2028b-5ecd-400d-a280-84ea92dd2f9b.png)

Which we are passing here as the configuration of wasm loader,

```
      const wasmLoader = {
        test: /\.wasm$/,
        exclude: /node_modules/,
        loaders: ['wasm-loader'],
      };

      addBeforeLoader(webpackConfig, loaderByName('file-loader'), wasmLoader);

```
My package.json dependencies:
```

    "@craco/craco": "^6.4.5",
    "@trinsic/trinsic": "^1.7.1-rc2",
    "@trinsic/trinsic-web": "^1.4.2",


```Please share your thoughts on this issue.

**Comment by janpieterz** [comment]
Thanks for filing this @kashyapshiv, we've been in contact through our Slack on this issue and should be close to a resolution.

**Comment by fundthmcalculus** [comment]
@janpieterz isn't this now fixed?

**Comment by janpieterz** [comment]
Yes it is, confirmed today.
