### ISSUE TITLE
Implement linters as PR checks

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#933]
We should code lint on PRs to ensure that all code is consistently formatted. This is currently done on the backend for the generated proto/sdk wrapper code, but we should apply it to user-edited code as well. The `.editorconfig` file is already [merged here](https://github.com/trinsic-id/sdk/pull/932).

Here are two options for linter actions:
~1. https://github.com/marketplace/actions/super-linter#supported-linters <- supports every language we use, and some that we don't (yet). - only gap is `prettier`~ The docker image for this action is so large it causes problems.
2. https://github.com/marketplace/actions/lint-action <- used this for some languages on okapi, but it doesn't support some formatters, eg Java, dart,

* We should have a separate pr validation action so that we don't run the linter on every os * every lang version.

The action should fail the PR as a separate check from the unit tests, so that the developer knows if the code is incorrectly formatted, and/or the unit tests are failing on CI without digging into the logs.

Languages:
- [ ] CLI - `cargo fmt` ?
- [x] ~Docs~ - not relevant
- [x] .NET - `dotnet format` 
- [x] Dart - `dart format` 
- [x] Go - `gofmt` 
- [x] Java - `google-java-format` 
- [x] Python - `black` 
- [x] Ruby - `rubocop` 
- [x] Swift - `swift format` (Official choice, need to use it) https://github.com/trinsic-id/sdk-swift/pull/47
- [x] Typescript - `prettier`

### My Opinions
We should use option 1, `Super Linter`, since it supports everything, including github action linters (which would be immensely helpful). We shouldn't make this action fail until we have everything already formatted, which would be done automatically by the protoc-gen-sdk action (which itself applies the relevant formatters before opening the PR for obvious reasons).

**Comment by fundthmcalculus** [comment]
@janpieterz tagging you for thoughts/opinions. @MichaelEdwardBlack if you'd like to collab on this as another github action pair-programming hack, I'd love to walk you through it! :)

**Comment by janpieterz** [comment]
@fundthmcalculus Pretty sure the super linter uses [a Prettier plugin for ESLint](https://prettier.io/docs/en/integrating-with-linters.html), see [the docs](https://github.com/github/super-linter) (search for `TYPESCRIPT_DEFAULT_STYLE` and `JAVASCRIPT_DEFAULT_STYLE`).

I think this would be a great `good first issue` as well, I'll chat to Chiara for next sprint or next week about this.

**Comment by fundthmcalculus** [comment]
I would be happy to help coach @chiarapaskulin through this if you would like!

**Comment by janpieterz** [comment]
Thanks, I might reach out for that whenever it lands around :)

**Comment by fundthmcalculus** [comment]
Playing around with this a bit due to boredom last night - it's not a `good-first-issue` since `superlinter` uses docker...

**Comment by chiarapaskulin** [comment]
oh :( thank you anyway @fundthmcalculus ! ❤️

**Comment by fundthmcalculus** [comment]
> oh :( thank you anyway @fundthmcalculus ! ❤️

there is a way to do this without `superlinter`, so we could probably do it. If you're familiar with docker, we can totally collab on it.

**Comment by chiarapaskulin** [comment]
Already did a project with it, but not super used/familiar. But if you think so, we definitely can! 😃

**Comment by fundthmcalculus** [comment]
@chiarapaskulin want to meet up on gather and knock this out?
