### ISSUE TITLE
Browser sample using webpack only doesn't result in a workable state

### ISSUE THREAD

**Issue by janpieterz** [Dentity-Development/dentity-ecosystems-sdk#937]
### Reproduction steps

1. Follow steps in [docs](https://docs-v2.trinsic.id/web/).
2. End result of using either React or Webpack only version doesn't result in something running locally that is workable.

- [x] fix bug
- [x] documentation

**Comment by fundthmcalculus** [comment]
This should be fixed now, right?

**Comment by janpieterz** [comment]
No not yet, I still need to rewrite the docs for this, following our revised samples. On my to-do list
