### ISSUE TITLE
Make sure all service SDKs support asynchronous communication

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#96]
Currently only .NET and Python do this.
- [x] Java  https://github.com/trinsic-id/sdk/pull/178
- [x] Go
- [x] Ruby (https://brunosutic.com/blog/async-ruby)
- [x] Swift (https://www.swiftbysundell.com/articles/connecting-async-await-with-other-swift-code)
- [x] C#
- [x] Python

**Comment by tmarkovski** [comment]
Rust, Node and Browser sdk also support asynchronous calls, I ... Promise 😁

**Comment by fundthmcalculus** [comment]
🥁 🤦

**Comment by fundthmcalculus** [comment]
TL-DR: Swift 5.5 (and later) will have good `async` / `await` support in the near future. Java never will, it has `CompleteableFuture<T>`, which is nowhere near as nice. Ruby 3.0 (and later) will have an `async` mixin.

**Comment by tmarkovski** [comment]
Thanks. Can we close this then?

**Comment by fundthmcalculus** [comment]
In my opinion, no. However, I don't think it's a beta release issue. We should revisit the issue once broader support is available. Aka, dropping Ruby 2.7, swift 5.5 is broadly available, etc.

**Comment by tmarkovski** [comment]
Ok, it's backlogged
