### ISSUE TITLE
Sample application to use `ProviderService`

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#97]
@michaeldboyd @tmarkovski , we need a sample application / large unit-test that consumes `ProviderService` so we can properly test it. Ideally, we have 100% coverage of all SDK endpoints.

**Comment by michaelboyd** [comment]
Hi Scott,

I believe you are trying to reach a different michaeldboyd, which is here:
https://github.com/michaeldboyd ***@***.***)

I am also michaeldboyd but sometime back I think I took the 'd' out of my
username.  Not sure, but am confused by this, that much is certain. :)

Hope you get the sample app and everything you need.

Thanks,
Michael
