### ISSUE TITLE
Github Action & Package for Go

### ISSUE THREAD

**Issue by tmarkovski** [Dentity-Development/dentity-ecosystems-sdk#98]
We need a build and test action for golang services.
- [x] Release go okapi
- [x] ?Package the okapi binaries? - NO, readme tells how to download
- [x] ?Automatic download via python script (since golang is compiled)? - out of scope
- [x] Unit test
- [x] Release go services

**Comment by fundthmcalculus** [comment]
https://github.com/trinsic-id/sdk/pull/130
